prompt --application/deployment/install/install_demo_application_table
begin
--   Manifest
--     INSTALL: INSTALL-Demo Application Table
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(34855282644029862853)
,p_install_id=>wwv_flow_imp.id(20957044554869726037)
,p_name=>'Demo Application Table'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_option=>'TABLE'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE "CATEGORY" ',
'   (	"OID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOT NULL ENABLE, ',
'	"CAT_NAME_ENG" VARCHAR2(50), ',
'	"CAT_NAME_BANGLA" VARCHAR2(255), ',
'	"STATUS_ID" NUMBER, ',
'	"ADDED_DATE" DATE, ',
'	"CREATE_BY" VARCHAR2(50), ',
'	"UPDATE_DATE" VARCHAR2(4000), ',
'	 PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "PRODUCT" ',
'   (	"PRODUCT_ID" NUMBER, ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"PRODUCT_NAME" VARCHAR2(250), ',
'	"PRODUCT_DESCRIPTION" VARCHAR2(4000), ',
'	"PRODUCT_IMAGE" BLOB, ',
'	"CATEGORY" NUMBER, ',
'	"GROUP_NAME" VARCHAR2(250), ',
'	"STATUS_ID" VARCHAR2(50), ',
'	"CREATE_BY" VARCHAR2(250), ',
'	"CREATE_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"MIME_TYPE" VARCHAR2(250), ',
'	"ALL_SLIDE_ID" NUMBER, ',
'	 CONSTRAINT "PK_PRODUCT_ID" PRIMARY KEY ("PRODUCT_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "MENUS" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"PARENT_OID" NUMBER, ',
'	"MENU_NAME" NVARCHAR2(100), ',
'	"MENU_LINK" NVARCHAR2(200), ',
'	"STATUS" NVARCHAR2(1), ',
'	"DESCRIPTION" NVARCHAR2(200), ',
'	"SORT_BY" NUMBER, ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	"INSERT_DATE" DATE DEFAULT sysdate, ',
'	"ICON_IMG" VARCHAR2(250), ',
'	"MENU_NAME_BANGLA" VARCHAR2(250), ',
'	 CONSTRAINT "MENUS_C01" CHECK (parent_oid <> oid) ENABLE, ',
'	 CONSTRAINT "MENUS_CON_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "COUNTRY" ',
'   (	"OID" NUMBER, ',
'	"CNTR_ID" VARCHAR2(1), ',
'	"CNTR_NAME" VARCHAR2(255), ',
'	"IS_ACTIVE" NUMBER, ',
'	"CNTR_NAME1" VARCHAR2(255), ',
'	"PID_EMPLOYEE_INSERT_BY" VARCHAR2(1), ',
'	"INSERT_DATE" VARCHAR2(1), ',
'	"PID_EMPLOYEE_UPDATE_BY" VARCHAR2(1), ',
'	"UPDATE_DATE" VARCHAR2(1)',
'   ) ;',
'',
'CREATE TABLE "HTMLDB_PLAN_TABLE" ',
'   (	"STATEMENT_ID" VARCHAR2(30), ',
'	"PLAN_ID" NUMBER, ',
'	"TIMESTAMP" DATE, ',
'	"REMARKS" VARCHAR2(4000), ',
'	"OPERATION" VARCHAR2(30), ',
'	"OPTIONS" VARCHAR2(255), ',
'	"OBJECT_NODE" VARCHAR2(128), ',
'	"OBJECT_OWNER" VARCHAR2(128), ',
'	"OBJECT_NAME" VARCHAR2(128), ',
'	"OBJECT_ALIAS" VARCHAR2(261), ',
'	"OBJECT_INSTANCE" NUMBER(*,0), ',
'	"OBJECT_TYPE" VARCHAR2(128), ',
'	"OPTIMIZER" VARCHAR2(255), ',
'	"SEARCH_COLUMNS" NUMBER, ',
'	"ID" NUMBER(*,0), ',
'	"PARENT_ID" NUMBER(*,0), ',
'	"DEPTH" NUMBER(*,0), ',
'	"POSITION" NUMBER(*,0), ',
'	"COST" NUMBER(*,0), ',
'	"CARDINALITY" NUMBER(*,0), ',
'	"BYTES" NUMBER(*,0), ',
'	"OTHER_TAG" VARCHAR2(255), ',
'	"PARTITION_START" VARCHAR2(255), ',
'	"PARTITION_STOP" VARCHAR2(255), ',
'	"PARTITION_ID" NUMBER(*,0), ',
'	"OTHER" LONG, ',
'	"DISTRIBUTION" VARCHAR2(30), ',
'	"CPU_COST" NUMBER(*,0), ',
'	"IO_COST" NUMBER(*,0), ',
'	"TEMP_SPACE" NUMBER(*,0), ',
'	"ACCESS_PREDICATES" VARCHAR2(4000), ',
'	"FILTER_PREDICATES" VARCHAR2(4000), ',
'	"PROJECTION" VARCHAR2(4000), ',
'	"TIME" NUMBER(*,0), ',
'	"QBLOCK_NAME" VARCHAR2(128)',
'   ) ;',
'',
'CREATE TABLE "MY_USERS" ',
'   (	"USER_ID" NUMBER, ',
'	"USERNAME" VARCHAR2(50), ',
'	"FULL_NAME" VARCHAR2(100), ',
'	"PHONE_NUMBER" NUMBER(11,0), ',
'	"EMAIL_ADDRESS" VARCHAR2(50), ',
'	"IMAGE" BLOB, ',
'	"USER_TYPE" VARCHAR2(250), ',
'	"SHOP_CATEGORY" VARCHAR2(100), ',
'	"IS_ACTIVE" VARCHAR2(10), ',
'	"PASSWORD" VARCHAR2(50), ',
'	"CREATE_BY" VARCHAR2(50), ',
'	"ADDED_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"MIME_TYPE" VARCHAR2(250), ',
'	"PIN" VARCHAR2(4000), ',
'	"UPDATE_BY" VARCHAR2(250), ',
'	"PASSWORD_RECOVERY_CODE" VARCHAR2(150), ',
'	"FORGOT_PASSWORD_USE" VARCHAR2(150), ',
'	 CONSTRAINT "MY_USERS_PK" PRIMARY KEY ("USER_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "NOTI_CATEGORY" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"CATEGORY" VARCHAR2(100), ',
'	"ICON_IMG" VARCHAR2(1000)',
'   ) ;',
'',
'CREATE TABLE "PRODUCT_RATING" ',
'   (	"OID" NUMBER, ',
'	"PRODUCT_ID" NUMBER, ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"PRODUCT_NAME" VARCHAR2(250), ',
'	"START_DATE" DATE, ',
'	"PRODUCT_RATING" VARCHAR2(50), ',
'	"CREATE_BY" VARCHAR2(250), ',
'	"CREATE_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"UPDATE_BY" VARCHAR2(250), ',
'	 CONSTRAINT "PK_PRODUCT_RATING" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "REPORT_VIEW_LOG" ',
'   (	"OID" NUMBER, ',
'	"REPORT_NAME" NVARCHAR2(50), ',
'	"REPORT_DATE" DATE NOT NULL ENABLE, ',
'	"REF_PID" NUMBER, ',
'	"ACL_USER" NUMBER, ',
'	"PAGE_ID" NUMBER, ',
'	"IP" NVARCHAR2(50), ',
'	"CODE_ID" NVARCHAR2(30), ',
'	 PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "SALES_DTLS" ',
'   (	"OID" NUMBER, ',
'	"PRODUCT_ID" NUMBER, ',
'	"ITEM_NAME" VARCHAR2(100), ',
'	"PROOUCT_SIZE" NUMBER, ',
'	"QTY" NUMBER, ',
'	"TOTAL" NUMBER, ',
'	"SUBMIT" NUMBER, ',
'	"CREATED_BY" VARCHAR2(50), ',
'	"CREATE_DATE" DATE, ',
'	"INVNO" VARCHAR2(50), ',
'	"RATE" NUMBER, ',
'	"DISCOUNT" NUMBER, ',
'	"UPDATE_BY" VARCHAR2(50), ',
'	"UPDATE_DATE" DATE, ',
'	"IP" NUMBER',
'   ) ;',
'',
'CREATE TABLE "SALES_ORDER" ',
'   (	"OID" NUMBER, ',
'	"PRODUCT_QUANTITY" NUMBER, ',
'	"TOTAL_AMOUNT" NUMBER, ',
'	"DISCOUNTS" NUMBER, ',
'	"NOW_PAID" NUMBER, ',
'	"DUE" NUMBER, ',
'	"CASH_PAID" NUMBER, ',
'	"CHNAGE_AMOUNT" NUMBER, ',
'	"ADDED_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"STOCK_ID" NUMBER, ',
'	"SALE_QUANTITY" NUMBER, ',
'	"SALES_AMOUNT" NUMBER, ',
'	"CREATE_BY" VARCHAR2(100), ',
'	"INVOICE_NO" NUMBER, ',
'	"CUSTOMER_ID" NUMBER, ',
'	 CONSTRAINT "SALES_ORDER_CON" UNIQUE ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "NOTIFICATION" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"SUBJECT" VARCHAR2(100), ',
'	"MESSAGE" VARCHAR2(1000), ',
'	"CATEGORY" VARCHAR2(100), ',
'	"M_TO" VARCHAR2(500), ',
'	"STATUS_ID" NUMBER',
'   ) ;',
'',
'CREATE TABLE "POST_BLOG" ',
'   (	"OID" NUMBER, ',
'	"REPORT_NAME" NVARCHAR2(50), ',
'	"REPORT_title" VARCHAR2(60), ',
'	"meta_description" VARCHAR2(250), ',
'	"h2_title" VARCHAR2(450), ',
'	"paragraph" CLOB, ',
'	"REPORT_IMAGE" BLOB, ',
'	"MIME_TYPE" VARCHAR2(250), ',
'	"Filename_Column" VARCHAR2(250), ',
'	"Character_Set_Column" VARCHAR2(250), ',
'	"BLOB_Last_Updated_Column" DATE',
'   ) ;',
'',
'CREATE TABLE "SALES_MST" ',
'   (	"OID" NUMBER, ',
'	"INVNO" VARCHAR2(200), ',
'	"INVIO_DATE" DATE, ',
'	"CUST_ID" VARCHAR2(200), ',
'	"TOTAL" NUMBER(12,2), ',
'	"DISCOUNT" NUMBER(12,2), ',
'	"PAYMENT" NUMBER(12,2), ',
'	"CHANGE_AMOUNT" NUMBER, ',
'	"DUE" NUMBER(12,2), ',
'	"CREATED_BY" VARCHAR2(50), ',
'	"CREATE_DATE" DATE, ',
'	"UPDATE_BY" VARCHAR2(250), ',
'	"UPDATE_DATE" DATE, ',
'	"IP" VARCHAR2(250)',
'   ) ;',
'',
'CREATE TABLE "SUPPLIER" ',
'   (	"OID" NUMBER, ',
'	"SUPPLIER_NAME" VARCHAR2(250), ',
'	"MOBOLE_NO" NUMBER, ',
'	"OFFICIAL_NUMBER" NUMBER, ',
'	"COMPANY_NAME" VARCHAR2(250), ',
'	"ADDRESS" VARCHAR2(250), ',
'	"NOTE" VARCHAR2(250), ',
'	"PICTURE" BLOB, ',
'	"ADDED_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"CREATE_BY" VARCHAR2(100), ',
'	"MIME_TYPE" VARCHAR2(250), ',
'	"COUNTRY_OID" NUMBER, ',
'	"DISTRICT_OID" NUMBER, ',
'	"STATUS_ID" NUMBER',
'   ) ;',
'',
'CREATE TABLE "SURETY_ACCOUNT" ',
'   (	"OID" NUMBER, ',
'	"SURETY_OID" NUMBER NOT NULL ENABLE, ',
'	"BAILBOND_OID" NUMBER, ',
'	"TRANSACTION_DATE" DATE NOT NULL ENABLE, ',
'	"DESCRIPTION" NVARCHAR2(300), ',
'	"AMOUNT_DR" NUMBER DEFAULT 0, ',
'	"AMOUNT_CR" NUMBER DEFAULT 0, ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "SURETY_ACCOUNT_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "TAPEX_WORKSPACE_ACCESS_LOG" ',
'   (	"WORKSPACE" VARCHAR2(255) NOT NULL ENABLE, ',
'	"WORKSPACE_DISPLAY_NAME" VARCHAR2(4000), ',
'	"APPLICATION_ID" NUMBER, ',
'	"APPLICATION_NAME" VARCHAR2(255), ',
'	"USER_NAME" VARCHAR2(255), ',
'	"AUTHENTICATION_METHOD" VARCHAR2(255), ',
'	"APPLICATION_SCHEMA_OWNER" VARCHAR2(255), ',
'	"ACCESS_DATE" DATE, ',
'	"SECONDS_AGO" NUMBER, ',
'	"IP_ADDRESS" VARCHAR2(255), ',
'	"AUTHENTICATION_RESULT" VARCHAR2(40), ',
'	"CUSTOM_STATUS_TEXT" VARCHAR2(4000), ',
'	"WORKSPACE_ID" NUMBER',
'   ) ;',
'',
'CREATE TABLE "GALLERY" ',
'   (	"ID" NUMBER NOT NULL ENABLE, ',
'	"TITLE" VARCHAR2(1000) NOT NULL ENABLE, ',
'	"CONTENT_TYPE" VARCHAR2(1000) NOT NULL ENABLE, ',
'	"IMAGE" BLOB NOT NULL ENABLE, ',
'	 CONSTRAINT "GALLERY_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "THANAUPAZILA" ',
'   (	"OID" NUMBER, ',
'	"THAN_ID" NUMBER, ',
'	"THAN_NM" VARCHAR2(255), ',
'	"DIST_OID" NUMBER, ',
'	"IS_ACTIVE" NUMBER, ',
'	"THAN_NM1" VARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" NUMBER, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER',
'   ) ;',
'',
'CREATE TABLE "ITEM_SIZE" ',
'   (	"OID" NUMBER, ',
'	"SIZE_NAME" VARCHAR2(250), ',
'	"SHORT_NAME" VARCHAR2(250)',
'   ) ;',
'',
'CREATE TABLE "MY_FILE_TABLE" ',
'   (	"FILE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOT NULL ENABLE, ',
'	"FILE_NAME" VARCHAR2(255), ',
'	"SUBJECT" VARCHAR2(255), ',
'	"BLOB_CONTENT" BLOB, ',
'	"MIME_TYPE" VARCHAR2(255), ',
'	"DATE_CREATED" DATE, ',
'	 CONSTRAINT "MY_FILE_TABLE_PK" PRIMARY KEY ("FILE_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "POS_USER" ',
'   (	"USER_ID" NUMBER, ',
'	"USER_NAME" VARCHAR2(100), ',
'	"PASSWORD" VARCHAR2(4000), ',
'	"CREATED_ON" DATE, ',
'	"DEPARTMENT" VARCHAR2(200), ',
'	"AUT_SECTION" VARCHAR2(200), ',
'	"ADMIN_USER" CHAR(1), ',
'	"FACTORY_NAME" VARCHAR2(200), ',
'	"ACCESSCODE" NUMBER(20,0), ',
'	"ACTIVE" CHAR(2), ',
'	"PHOTO" BLOB, ',
'	"CREATED_BY" VARCHAR2(70)',
'   ) ;',
'',
'CREATE TABLE "REPORT_LOG" ',
'   (	"OID" NUMBER, ',
'	"REPORT_NAME" NVARCHAR2(150), ',
'	"REPORT_DATE" DATE, ',
'	"REF_ID" NVARCHAR2(50), ',
'	"PID_ACL_USER" NVARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	"REPORTING_DATE" DATE, ',
'	 CONSTRAINT "REPORT_LOG_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "ACL_USER_GROUP" ',
'   (	"OID" NUMBER, ',
'	"PID_USER" NUMBER, ',
'	"PID_GROUP" NUMBER, ',
'	"IS_ACTIVE" NVARCHAR2(1), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "ACL_USER_GROUP_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "COURT" ',
'   (	"OID" NUMBER(*,0), ',
'	"COURT_ID" VARCHAR2(3), ',
'	"COURT_NM" NVARCHAR2(100), ',
'	"IS_ACTIVE" NUMBER(*,0), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	"DIVI_OID" NUMBER',
'   ) ;',
'',
'CREATE TABLE "E_LOG" ',
'   (	"PID" NUMBER, ',
'	"MSG" NVARCHAR2(300), ',
'	"ERR_DATE" DATE DEFAULT sysdate',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "MY_IMPORTENT_CODE" ',
'   (	"OID" NUMBER, ',
'	"THE_NAME_OF_THE_CODE" VARCHAR2(200), ',
'	"FULL_SCRIPT" VARCHAR2(4000), ',
'	"NOTE" VARCHAR2(4000)',
'   ) ;',
'',
'CREATE TABLE "ALL_LANGUAGES" ',
'   (	"ID" NUMBER NOT NULL ENABLE, ',
'	"CODE" VARCHAR2(10) NOT NULL ENABLE, ',
'	"LANGUAGE" VARCHAR2(200) NOT NULL ENABLE, ',
'	"TEXT_DIRECTION" VARCHAR2(10), ',
'	"CREATED_BY" VARCHAR2(255), ',
'	"CREATED_ON" DATE, ',
'	"UPDATED_BY" VARCHAR2(255), ',
'	"UPDATED_ON" DATE',
'   ) ;',
'',
'CREATE TABLE "COLOR" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"COLOR_NAME" VARCHAR2(100), ',
'	 PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "PRODUCT_DETELS" ',
'   (	"PRODUCT_DETELS_ID" NUMBER, ',
'	"PRODUCT_ID" NUMBER, ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"COLOR" VARCHAR2(250), ',
'	"FABRIC" VARCHAR2(250), ',
'	"GENDER" VARCHAR2(250), ',
'	"STYLE" VARCHAR2(250), ',
'	"BRAND" VARCHAR2(250), ',
'	"PRODUCT_TYPE" VARCHAR2(250), ',
'	"OTHERS" VARCHAR2(250), ',
'	 CONSTRAINT "PK_PRODUCT_DETELS_ID" PRIMARY KEY ("PRODUCT_DETELS_ID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "PRODUCT_DETELS_UNI" UNIQUE ("PRODUCT_ID", "PRODUCT_CODE")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "PURCHASE_DETALIS" ',
'   (	"OID" NUMBER, ',
'	"VOUCHER_NO" VARCHAR2(200), ',
'	"PRODUCT_ID" VARCHAR2(50), ',
'	"ITEM_NAME" VARCHAR2(250), ',
'	"PROOUCT_SIZE" VARCHAR2(50), ',
'	"CPU" NUMBER, ',
'	"QTY" NUMBER, ',
'	"TOTAL" NUMBER, ',
'	"SUBMIT" NUMBER, ',
'	"CREATE_DATE" DATE, ',
'	"RETERN_PRODUCT" VARCHAR2(50), ',
'	"REFUND_TO_CUSTOMER" NUMBER, ',
'	"RPU" NUMBER',
'   ) ;',
'',
'CREATE TABLE "USER_GROUP_MY_STOCK" ',
'   (	"PID" NUMBER NOT NULL ENABLE, ',
'	"PID_USER" NUMBER NOT NULL ENABLE, ',
'	"PID_GROUP" NUMBER NOT NULL ENABLE, ',
'	"IS_ACTIVE" VARCHAR2(1), ',
'	"INSERT_BY" VARCHAR2(200), ',
'	"UPDATE_BY" VARCHAR2(200), ',
'	"UPDATE_DATE" DATE, ',
'	"INSERT_DATE" DATE, ',
'	 CONSTRAINT "USER_GROUP_MY_STOCK_PK" PRIMARY KEY ("PID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "USER_GROUP_PAGE_ACCESS" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"PID_GROUP" NUMBER NOT NULL ENABLE, ',
'	"PAGE_ID" NUMBER, ',
'	"PERMISSION" NUMBER(1,0) DEFAULT 1, ',
'	 CONSTRAINT "ACL_GROUP_PAGE_ACCESS_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "ACL_GROUP_PAGE_ACCESS_U01" UNIQUE ("PID_GROUP", "PAGE_ID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "MENUS_ACCESS" ',
'   (	"OID" NUMBER, ',
'	"GROUP_OID" NUMBER, ',
'	"MENU_OID" NUMBER, ',
'	"MENU_LINK_PAGENO" NUMBER',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "STOCK" ',
'   (	"PRODUCT_ID" VARCHAR2(200), ',
'	"PROOUCT_SIZE" VARCHAR2(200), ',
'	"IN_QNTY" NUMBER, ',
'	"OUT_QNTY" NUMBER, ',
'	"STK_QNTY" NUMBER',
'   ) ;',
'',
'CREATE TABLE "UNIT" ',
'   (	"OID" NUMBER, ',
'	"UNIT_ID" VARCHAR2(1), ',
'	"UNIT_NM" VARCHAR2(255), ',
'	"COURT_OID" NUMBER, ',
'	"IS_ACTIVE" NUMBER, ',
'	"THANAUPAZILA_OID" VARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" VARCHAR2(50), ',
'	"INSERT_DATE" VARCHAR2(50), ',
'	"PID_EMPLOYEE_UPDATE_BY" VARCHAR2(50), ',
'	"UPDATE_DATE" VARCHAR2(50), ',
'	"IS_REPORTABLE" VARCHAR2(1)',
'   ) ;',
'',
'CREATE TABLE "IS_ACTIVATE" ',
'   (	"OID" NUMBER, ',
'	"STATUS" VARCHAR2(30), ',
'	 CONSTRAINT "IS_ACTIVATE_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "TAPEX_WORKSPACE_ACTIVITY_LOG" ',
'   (	"WORKSPACE" VARCHAR2(255), ',
'	"WORKSPACE_DISPLAY_NAME" VARCHAR2(4000), ',
'	"APEX_USER" VARCHAR2(255), ',
'	"APPLICATION_ID" NUMBER, ',
'	"APPLICATION_NAME" VARCHAR2(255), ',
'	"APPLICATION_SCHEMA_OWNER" VARCHAR2(255), ',
'	"PAGE_ID" NUMBER, ',
'	"PAGE_NAME" VARCHAR2(255), ',
'	"VIEW_DATE" DATE, ',
'	"THINK_TIME" NUMBER, ',
'	"SECONDS_AGO" NUMBER, ',
'	"LOG_CONTEXT" VARCHAR2(255), ',
'	"ELAPSED_TIME" NUMBER, ',
'	"ROWS_QUERIED" NUMBER, ',
'	"IP_ADDRESS" VARCHAR2(4000), ',
'	"AGENT" VARCHAR2(4000), ',
'	"APEX_SESSION_ID" NUMBER, ',
'	"APPLICATION_TENANT_ID" VARCHAR2(255), ',
'	"ERROR_MESSAGE" VARCHAR2(4000), ',
'	"ERROR_ON_COMPONENT_TYPE" VARCHAR2(255), ',
'	"ERROR_ON_COMPONENT_NAME" VARCHAR2(255), ',
'	"PAGE_VIEW_MODE" VARCHAR2(255), ',
'	"APPLICATION_INFO" VARCHAR2(255), ',
'	"INTERACTIVE_REPORT_ID" NUMBER, ',
'	"IR_SAVED_REPORT_ID" NUMBER, ',
'	"IR_SEARCH" VARCHAR2(4000), ',
'	"WS_APPLICATION_ID" NUMBER, ',
'	"WS_PAGE_ID" NUMBER, ',
'	"WS_DATAGRID_ID" NUMBER, ',
'	"CONTENT_LENGTH" NUMBER, ',
'	"REGIONS_FROM_CACHE" NUMBER, ',
'	"WORKSPACE_ID" NUMBER, ',
'	"PAGE_VIEW_TYPE" VARCHAR2(255), ',
'	"REQUEST_VALUE" VARCHAR2(4000), ',
'	"DEBUG_PAGE_VIEW_ID" NUMBER, ',
'	"VIEW_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, ',
'	"ECID" VARCHAR2(255)',
'   ) ;',
'',
'CREATE TABLE "USER_LOC" ',
'   (	"ID" NUMBER, ',
'	"USER_NAME" VARCHAR2(250), ',
'	"LATITUDE" VARCHAR2(250), ',
'	"LONGITUDE" VARCHAR2(250), ',
'	"LOC_DATE" DATE',
'   ) ;',
'',
'CREATE TABLE "EMP" ',
'   (	"EMPNO" NUMBER(4,0) NOT NULL ENABLE, ',
'	"ENAME" VARCHAR2(10), ',
'	"JOB" VARCHAR2(9), ',
'	"MGR" NUMBER(4,0), ',
'	"HIREDATE" DATE, ',
'	"SAL" NUMBER(7,2), ',
'	"COMM" NUMBER(7,2), ',
'	"DEPTNO" NUMBER(2,0), ',
'	 PRIMARY KEY ("EMPNO")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "LIKE_TABLE" ',
'   (	"OID" NUMBER, ',
'	"LIKE1" NUMBER, ',
'	"UN_LIKE" NUMBER, ',
'	"USER_ID" VARCHAR2(150), ',
'	"USER_NAME" VARCHAR2(150)',
'   ) ;',
'',
'CREATE TABLE "MY_SHOP_NAME" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"SHOP_NAME" VARCHAR2(250), ',
'	"ADDRESS" VARCHAR2(250), ',
'	"MOBOLE_NO" VARCHAR2(250), ',
'	"EMAIL" VARCHAR2(250), ',
'	"DESCRIPTION" VARCHAR2(250), ',
'	"CREATE_BY" VARCHAR2(50), ',
'	"ADDED_DATE" DATE, ',
'	"UPDATE_DATE" DATE',
'   ) ;',
'',
'CREATE TABLE "PURCHASE_MASTER" ',
'   (	"OID" NUMBER, ',
'	"VOUCHER_NO" VARCHAR2(200), ',
'	"SUPPLIER_NAME" VARCHAR2(50), ',
'	"DATE1" DATE, ',
'	"TOTAL" NUMBER, ',
'	"DISCOUNT" NUMBER, ',
'	"CREATED_BY" VARCHAR2(50), ',
'	"CREATED_NO" DATE, ',
'	"VAT" NUMBER, ',
'	"SUB_TOTAL" NUMBER, ',
'	 CONSTRAINT "PURCHASE_MASTER_PK" PRIMARY KEY ("VOUCHER_NO")',
'  USING INDEX (CREATE UNIQUE INDEX "PURCHASE_MASTER_IDX1" ON "PURCHASE_MASTER" ("VOUCHER_NO") ',
'  )  ENABLE',
'   ) ;',
'',
'CREATE TABLE "USERS_LOG" ',
'   (	"LOG_ID" NUMBER, ',
'	"IP_ADDRESS" VARCHAR2(30), ',
'	"LOGIN_USER" VARCHAR2(30), ',
'	"LOGIN_TIME" TIMESTAMP (6), ',
'	"LOGOUT_TIME" TIMESTAMP (6), ',
'	"LOG_DATE" DATE, ',
'	"CREATED" VARCHAR2(250), ',
'	"CREATED_BY" VARCHAR2(250), ',
'	"UPDATED_BY" VARCHAR2(250), ',
'	"UPDATED" VARCHAR2(250)',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "ASSET" ',
'   (	"ASSET_ID" NUMBER, ',
'	"ACTIVE" VARCHAR2(1), ',
'	"CREATE_DATE" DATE, ',
'	"CREATED_BY" VARCHAR2(30), ',
'	"UPDATE_BY" DATE, ',
'	"UPDATE_DATE" VARCHAR2(30)',
'   ) ;',
'',
'CREATE TABLE "BRAND" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"BRAND_NAME" VARCHAR2(250), ',
'	"STATUS_ID" NUMBER, ',
'	"ADDED_DATE" VARCHAR2(250), ',
'	"UPDATE_DATE" VARCHAR2(250), ',
'	"CREATE_BY" VARCHAR2(100), ',
'	 CONSTRAINT "BRAND_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "CUSTOMER" ',
'   (	"OID" NUMBER, ',
'	"CUSTOMER_NAME" VARCHAR2(250), ',
'	"MOBOLE_NO" NUMBER, ',
'	"ADDRESS" VARCHAR2(250), ',
'	"NOTE" VARCHAR2(250), ',
'	"PICTURE" BLOB, ',
'	"PRODUCT_ID" VARCHAR2(250), ',
'	"STATUS_ID" VARCHAR2(250), ',
'	"BRAND_ID" VARCHAR2(250), ',
'	"CATEGORY_ID" VARCHAR2(250), ',
'	"ADDED_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	"CREATE_BY" VARCHAR2(100), ',
'	"MIME_TYPE" VARCHAR2(250), ',
'	"COUNTRY_OID" NUMBER, ',
'	"DISTRICT_OID" NUMBER',
'   ) ;',
'',
'CREATE TABLE "DISTRICT" ',
'   (	"OID" NUMBER, ',
'	"DIST_ID" VARCHAR2(50), ',
'	"DIST_NM" VARCHAR2(255), ',
'	"DIVI_OID" NUMBER, ',
'	"IS_ACTIVE" NUMBER, ',
'	"DIST_NM1" VARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" VARCHAR2(1), ',
'	"INSERT_DATE" VARCHAR2(1), ',
'	"PID_EMPLOYEE_UPDATE_BY" VARCHAR2(1), ',
'	"UPDATE_DATE" VARCHAR2(1)',
'   ) ;',
'',
'CREATE TABLE "DIVISION" ',
'   (	"OID" NUMBER, ',
'	"DIVI_ID" NUMBER, ',
'	"DIVI_NM" VARCHAR2(255), ',
'	"CNTR_OID" NUMBER, ',
'	"IS_ACTIVE" NUMBER, ',
'	"DIVI_NM1" VARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" VARCHAR2(1), ',
'	"INSERT_DATE" VARCHAR2(1), ',
'	"PID_EMPLOYEE_UPDATE_BY" VARCHAR2(1), ',
'	"UPDATE_DATE" VARCHAR2(1)',
'   ) ;',
'',
'CREATE TABLE "DEPT" ',
'   (	"DEPTNO" NUMBER(2,0), ',
'	"DNAME" VARCHAR2(14), ',
'	"LOC" VARCHAR2(13), ',
'	 PRIMARY KEY ("DEPTNO")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "SLIDESHOW_IMG" ',
'   (	"OID" NUMBER, ',
'	"IMAGE" BLOB, ',
'	"MIME_TYPE" VARCHAR2(100), ',
'	"FILE_NAME" VARCHAR2(100), ',
'	"LAST_UPDATE_DATE" DATE, ',
'	"SET_COLUMN" VARCHAR2(100), ',
'	"IMAGE_NO" NUMBER, ',
'	"SLIDER_TEXT" VARCHAR2(100), ',
'	"SLIDER_LINK" VARCHAR2(100), ',
'	 CONSTRAINT "PK_SLIDESHOW_IMG" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "STUDENT" ',
'   (	"STUDENT_ID" NUMBER, ',
'	"STUDENT_NAME" VARCHAR2(250), ',
'	"ADDRESS" VARCHAR2(250), ',
'	"PHONE" NUMBER, ',
'	"DATE1" DATE, ',
'	 CONSTRAINT "STUDENT_CON" PRIMARY KEY ("STUDENT_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "ALL_AUDIT_LOG" ',
'   (	"PID" NUMBER, ',
'	"T_OID" NUMBER, ',
'	"DATA" CLOB, ',
'	"TABLE_NAME" NVARCHAR2(100), ',
'	"PID_ACL_USER" NUMBER, ',
'	"TRANSECTION_DATE" DATE, ',
'	"ACTION_TYPE" NVARCHAR2(50), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	"IP" NVARCHAR2(20), ',
'	"INFO_OID" NUMBER',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "INFOFOLLOWUP" ',
'   (	"OID" NUMBER(*,0), ',
'	"INFO_OID" NUMBER(*,0) NOT NULL ENABLE, ',
'	"INFOFOLW_TITL" NVARCHAR2(500), ',
'	"INFOFOLW_SUB_TITL" NVARCHAR2(2000), ',
'	"INFOFOLW_DT" DATE NOT NULL ENABLE, ',
'	"INFOFOLW_REMK" NVARCHAR2(2000), ',
'	"INFOFOLW_MORE_DETA" NVARCHAR2(2000), ',
'	"INFOFLOW_DEAL_DT" DATE DEFAULT NULL, ',
'	"INFOFLOW_NEXT_DT" DATE, ',
'	"FOLWUP_STAG_MAJR_OID" NUMBER(*,0) NOT NULL ENABLE, ',
'	"INFOFOLLOWUP_CODE" NVARCHAR2(100), ',
'	"FOLWUP_SUB_STAG_OID" NUMBER(*,0) NOT NULL ENABLE, ',
'	"INFOFOLW_DEAL_UPDATE" DATE DEFAULT NULL, ',
'	"FOLLOWUP_STATUS_OID" NUMBER(*,0) DEFAULT 0, ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "PK_INFOFOLLOWUP" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "PRODUCT_PRICE" ',
'   (	"PRODUCT_PRICE_OID" NUMBER, ',
'	"PRODUCT_ID" NUMBER, ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"COST_PRICE" NUMBER, ',
'	"SELLING_PRICE" NUMBER, ',
'	"DISCOUNT" NUMBER, ',
'	"ORIGINAL_PRICE" NUMBER, ',
'	"STATUS_ID" VARCHAR2(50), ',
'	"CREATE_BY" VARCHAR2(250), ',
'	"CREATE_DATE" DATE, ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "PK_PRODUCT_PRICE_OID" PRIMARY KEY ("PRODUCT_PRICE_OID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "PRODUCT_PRICE_UNI" UNIQUE ("PRODUCT_ID", "PRODUCT_CODE")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "RETERN_PURCHASE_DETALIS" ',
'   (	"OID" NUMBER, ',
'	"VOUCHER_NO" VARCHAR2(200), ',
'	"PRODUCT_ID" VARCHAR2(50), ',
'	"ITEM_NAME" VARCHAR2(250), ',
'	"PROOUCT_SIZE" VARCHAR2(50), ',
'	"CPU" NUMBER, ',
'	"QTY" NUMBER, ',
'	"TOTAL" NUMBER, ',
'	"SUBMIT" NUMBER, ',
'	"CREATED_BY" VARCHAR2(50), ',
'	"CREATE_DATE" DATE, ',
'	"ACTION" VARCHAR2(50)',
'   ) ;',
'',
'CREATE TABLE "TREE_MENU" ',
'   (	"PARENT_NODE" NUMBER(*,0), ',
'	"CHILD_NODE" NUMBER(*,0), ',
'	"MENU_DESC" VARCHAR2(50), ',
'	"PAGE_NO" NUMBER(*,0), ',
'	 PRIMARY KEY ("PARENT_NODE")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "USER_GROUP" ',
'   (	"OID" NUMBER, ',
'	"PID_PARENT" NUMBER, ',
'	"GROUP_TITLE" NVARCHAR2(30), ',
'	"GROUP_DESCRIPTION" NVARCHAR2(250), ',
'	"IS_ACTIVE" NVARCHAR2(1), ',
'	"Create_By" VARCHAR2(200), ',
'	"Create_Date" DATE, ',
'	"Update By" VARCHAR2(200), ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "ACL_GROUP_PK" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "APX$ERR$EMP$679256" ',
'   (	"ORA_ERR_NUMBER$" NUMBER, ',
'	"ORA_ERR_MESG$" VARCHAR2(2000), ',
'	"ORA_ERR_ROWID$" UROWID (4000), ',
'	"ORA_ERR_OPTYP$" VARCHAR2(2), ',
'	"ORA_ERR_TAG$" VARCHAR2(2000), ',
'	"EMPNO" VARCHAR2(4000), ',
'	"ENAME" VARCHAR2(4000), ',
'	"JOB" VARCHAR2(4000), ',
'	"MGR" VARCHAR2(4000), ',
'	"HIREDATE" VARCHAR2(4000), ',
'	"SAL" VARCHAR2(4000), ',
'	"COMM" VARCHAR2(4000), ',
'	"DEPTNO" VARCHAR2(4000)',
'   ) ;',
'',
'CREATE TABLE "EXPORT_CLOB" ',
'   (	"APP_EXPORT" CLOB, ',
'	"APP_ID" VARCHAR2(5)',
'   ) ;',
'',
'CREATE TABLE "IMAGES" ',
'   (	"ID" NUMBER(10,0) NOT NULL ENABLE, ',
'	"NAME" VARCHAR2(50) NOT NULL ENABLE, ',
'	"IMAGE" BLOB NOT NULL ENABLE, ',
'	 CONSTRAINT "IMAGES_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "IMAGES_UK" UNIQUE ("NAME")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "DOB" ',
'   (	"OID" NUMBER(*,0), ',
'	"DOB" DATE NOT NULL ENABLE, ',
'	"DOB_TYPE_OID" NUMBER(*,0), ',
'	"DOB_MAJO" NUMBER(*,0), ',
'	"PERSON_OID" NUMBER(*,0), ',
'	"PID_EMPLOYEE_INSERT_BY" NUMBER, ',
'	"INSERT_DATE" DATE, ',
'	"PID_EMPLOYEE_UPDATE_BY" NUMBER, ',
'	"UPDATE_DATE" DATE, ',
'	 CONSTRAINT "PK_DOB" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "UK_DOB" UNIQUE ("DOB_TYPE_OID", "PERSON_OID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "USER_LOG_WEB" ',
'   (	"LOG_ID" NUMBER, ',
'	"USER_ID" VARCHAR2(100), ',
'	"USER_CODE" VARCHAR2(100), ',
'	"SESSION_ID" VARCHAR2(100), ',
'	"IN_TIME" DATE, ',
'	"REMOTE_ADDR" VARCHAR2(300), ',
'	"HTTP_HOST" VARCHAR2(300), ',
'	"REMOTE_USER" VARCHAR2(200), ',
'	"HTTP_USER_AGENT" VARCHAR2(200), ',
'	"HTTP_COOKIE" VARCHAR2(100), ',
'	"HTTP_REFERER" VARCHAR2(100), ',
'	"REQUEST_METHOD" VARCHAR2(400), ',
'	"REQUEST_PROTOCOL" VARCHAR2(100), ',
'	"SERVER_NAME" VARCHAR2(200), ',
'	"SERVER_PORT" VARCHAR2(50), ',
'	"SERVER_PROTOCOL" VARCHAR2(100), ',
'	"BROWSER_VERSION" VARCHAR2(100), ',
'	"REC_STATUS" VARCHAR2(200), ',
'	"CAPTCHA_VALUE" VARCHAR2(200), ',
'	"MAC_ADDRESS" VARCHAR2(500), ',
'	"VALID_LOGIN" VARCHAR2(100), ',
'	"LOGIN_FAILED_CODE" VARCHAR2(100), ',
'	"LOGIN_FAILED_ERROR" VARCHAR2(100), ',
'	"PC_NAME" VARCHAR2(100), ',
'	"OS_USER" VARCHAR2(100), ',
'	"OS_INFO" VARCHAR2(100), ',
'	"DNS" VARCHAR2(100), ',
'	"IP" VARCHAR2(200), ',
'	"LATITUDE" VARCHAR2(100), ',
'	"LONGITUDE" VARCHAR2(200), ',
'	"LOCATION" VARCHAR2(200), ',
'	"COUNTRY" VARCHAR2(100), ',
'	 CONSTRAINT "LOG_ID_PK" PRIMARY KEY ("LOG_ID")',
'  USING INDEX  ENABLE',
'   )  ENABLE ROW MOVEMENT ;',
'',
'CREATE TABLE "USER_TABLE_LOG" ',
'   (	"LOGE_ID" NUMBER, ',
'	"TABLE_NAME" VARCHAR2(250), ',
'	"PRODUCT_ID" VARCHAR2(250), ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"PRODUCT_NAME" VARCHAR2(250), ',
'	"ACTION" VARCHAR2(250), ',
'	"ADDED_DATE" DATE, ',
'	"CREATE_BY" VARCHAR2(250), ',
'	"IP" VARCHAR2(250), ',
'	 CONSTRAINT "USER_TABLE_LOG_CON" PRIMARY KEY ("LOGE_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "GROUP_NAME" ',
'   (	"OID" NUMBER, ',
'	"GROUP_NAME_ENG" VARCHAR2(50), ',
'	"GROUP_NAME_BANGLA" VARCHAR2(255), ',
'	"CATEGORY" NUMBER, ',
'	"STATUS_ID" NUMBER, ',
'	"CREATE_BY" VARCHAR2(50), ',
'	"CREATE_DATE" DATE, ',
'	"UPDATE_DATE" DATE',
'   ) ;',
'',
'CREATE TABLE "ORDER_PRODUCT" ',
'   (	"OID" NUMBER, ',
'	"PRODUCT_CODE" VARCHAR2(250), ',
'	"PRODUCT_NAME" VARCHAR2(250), ',
'	"RATE" NUMBER, ',
'	"QTY" NUMBER, ',
'	"USER_NAME" VARCHAR2(250), ',
'	"ORDER_DATE" DATE, ',
'	"CONFIRM_ORDER" VARCHAR2(150), ',
'	"CANCEL_ORDER" VARCHAR2(150), ',
'	"PRODUCT_ID" NUMBER, ',
'	"TOTAL" NUMBER, ',
'	 CONSTRAINT "ORDER_PRODUCT_CON" PRIMARY KEY ("OID")',
'  USING INDEX (CREATE UNIQUE INDEX "ORDER_PRODUCT_IDX1" ON "ORDER_PRODUCT" ("OID") ',
'  )  ENABLE',
'   ) ;',
'',
'CREATE TABLE "APPS_NAME" ',
'   (	"OID" NUMBER NOT NULL ENABLE, ',
'	"APP_NAME" VARCHAR2(4000), ',
'	"CURRENTLY_ACTIVE" NUMBER, ',
'	 CONSTRAINT "PK_OID" PRIMARY KEY ("OID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "TAST_LOCTION" ',
'   (	"OID" NUMBER, ',
'	"Address_Item" VARCHAR2(250), ',
'	"City_Item" VARCHAR2(250), ',
'	"State_Item" VARCHAR2(250), ',
'	"Zip_Code_Item" DATE, ',
'	"Country_Item" VARCHAR2(250), ',
'	"Latitude " VARCHAR2(250), ',
'	"Longitude  " VARCHAR2(250)',
'   ) ;',
'',
'CREATE TABLE "TEST" ',
'   (	"ID" NUMBER, ',
'	"PRODUCT" VARCHAR2(50), ',
'	"SALES_" VARCHAR2(50), ',
'	"CUSTOMER" VARCHAR2(50), ',
'	"SUPPLIER" VARCHAR2(50), ',
'	"INFO_CODE" NUMBER, ',
'	 CONSTRAINT "TEST_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "USER_PAGE" ',
'   (	"PID" NUMBER, ',
'	"PAGE_ID" NUMBER, ',
'	"PAGE_NAME" VARCHAR2(255), ',
'	"DESCRIPTION" VARCHAR2(4000), ',
'	"APP_ID" NUMBER, ',
'	"STATUS" NUMBER, ',
'	"USER_NAME" VARCHAR2(100), ',
'	 CONSTRAINT "CHECK_PAGE_ID" CHECK ( "PAGE_ID" IS NOT NULL) ENABLE, ',
'	 CONSTRAINT "USER_PAGE_PK" PRIMARY KEY ("PID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "USER_PAGE_UK1" UNIQUE ("PAGE_ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_CATEGORY_CON" FOREIGN KEY ("CATEGORY")',
'	  REFERENCES "CATEGORY" ("OID") ENABLE;',
'',
'ALTER TABLE "MENUS" ADD CONSTRAINT "MENUS_CON" FOREIGN KEY ("PARENT_OID")',
'	  REFERENCES "MENUS" ("OID") ENABLE;',
'',
'CREATE INDEX "PID_ALL_AUDIT_LOG_INDX" ON "ALL_AUDIT_LOG" ("PID") ',
'  ;',
'',
'CREATE UNIQUE INDEX "COURT_IDX1" ON "COURT" ("OID") ',
'  ;',
'',
'CREATE INDEX "E_LOG_PID_IDX" ON "E_LOG" ("PID") ',
'  ;',
'',
'CREATE UNIQUE INDEX "SYS_C0094981678" ON "GROUP_NAME" ("OID") ',
'  ;',
'',
'CREATE UNIQUE INDEX "PURCHASE_DETALIS_PK" ON "PURCHASE_DETALIS" ("OID") ',
'  ;',
'',
'CREATE INDEX "IDX_REP_DT" ON "REPORT_LOG" ("REPORTING_DATE") ',
'  ;',
'',
'CREATE UNIQUE INDEX "RETERN_PURCHASE_DETALIS_PK" ON "RETERN_PURCHASE_DETALIS" ("OID") ',
'  ;',
'',
'CREATE UNIQUE INDEX "SALES_MST_CON" ON "SALES_MST" ("OID") ',
'  ;',
'',
'CREATE INDEX "ACL_USERLOG_IPADD_IDX" ON "USERS_LOG" ("IP_ADDRESS") ',
'  ;',
'',
'CREATE INDEX "LOG_ID_ACL_USER_LOG_IDX" ON "USERS_LOG" ("LOG_ID", "LOGIN_USER") ',
'  ;',
'',
'CREATE INDEX "LOG_ID_ACL_USER_LOG_INDX" ON "USERS_LOG" ("LOG_ID") ',
'  ;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "AUTO_AUDIT_LOG_00141" ',
'   AFTER INSERT OR UPDATE OR DELETE',
'   ON MENUS_ACCESS',
'   FOR EACH ROW',
'DECLARE',
'   V_ACT_TYPE   VARCHAR2 (1);',
'   VT_PID       NUMBER;',
'   V_PID        NUMBER;',
'BEGIN',
'   IF INSERTING',
'   THEN',
'      V_ACT_TYPE := ''I'';',
'      VT_PID := :NEW.OID;',
'   ELSIF UPDATING',
'   THEN',
'      V_ACT_TYPE := ''U'';',
'      VT_PID := :OLD.OID;',
'   ELSE',
'      V_ACT_TYPE := ''D'';',
'      VT_PID := :OLD.OID;',
'   END IF;',
'   V_PID := pkg_primekey.fnc_primekey (p_nameofseq => ''ALL_ADT_LOG_SEQ'');',
'   INSERT INTO ALL_AUDIT_LOG (PID,',
'                              TABLE_NAME,',
'                              T_OID,',
'                              TRANSECTION_DATE,',
'                              ACTION_TYPE,',
'                              IP,',
'                              PID_ACL_USER,',
'                              DATA)',
'        VALUES (',
'                  V_PID,',
'                  ''MENUS_ACCESS'',',
'                  VT_PID,',
'                  SYSDATE,',
'                  V_ACT_TYPE,',
'                  OWA_UTIL.get_cgi_env (''REMOTE_ADDR''),',
'                  acl.get_current_user_pid,',
'                     ''<?xml version="1.0"?><ROWSET><MENUS_ACCESS><OID><OLD>''',
'                  || :OLD.OID',
'                  || ''</OLD><NEW>''',
'                  || :NEW.OID',
'                  || ''</NEW></OID><GROUP_OID><OLD>''',
'                  || :OLD.GROUP_OID',
'                  || ''</OLD><NEW>''',
'                  || :NEW.GROUP_OID',
'                  || ''</NEW></GROUP_OID><MENU_OID><OLD>''',
'                  || :OLD.MENU_OID',
'                  || ''</OLD><NEW>''',
'                  || :NEW.MENU_OID',
'                  || ''</NEW></MENU_OID><MENU_LINK_PAGENO><OLD>''',
'                  || :OLD.MENU_LINK_PAGENO',
'                  || ''</OLD><NEW>''',
'                  || :NEW.MENU_LINK_PAGENO',
'                  || ''</NEW></MENU_LINK_PAGENO></MENUS_ACCESS></ROWSET>'');',
'EXCEPTION',
'   WHEN OTHERS',
'   THEN',
'      RAISE;',
'END;',
'',
'/',
'',
'',
'ALTER TRIGGER "AUTO_AUDIT_LOG_00141" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "AUTO_AUDIT_LOG_0087" ',
'  BEFORE INSERT OR UPDATE OR DELETE ',
'  ON REPORT_LOG ',
'  REFERENCING NEW AS NEW OLD AS OLD ',
'  FOR EACH ROW ',
'DECLARE ',
'  V_ACT_TYPE   VARCHAR2 (1); ',
'  VT_PID       NUMBER; ',
'BEGIN ',
'  IF INSERTING ',
'  THEN ',
'     V_ACT_TYPE := ''I''; ',
'     VT_PID := :NEW.OID; ',
'  ELSIF UPDATING ',
'  THEN ',
'     V_ACT_TYPE := ''U''; ',
'     VT_PID := :OLD.OID; ',
'  ELSE ',
'     V_ACT_TYPE := ''D''; ',
'     VT_PID := :OLD.OID; ',
'  END IF; ',
'-- ',
'  INSERT INTO ALL_AUDIT_LOG (PID, ',
'                                  TABLE_NAME, ',
'                                  T_OID, ',
'                                  TRANSECTION_DATE, ',
'                                  ACTION_TYPE, ',
'                                  PID_ACL_USER, ',
'                                  DATA) ',
'      VALUES ( (    SELECT NVL (MAX (PID), 0) + 1 FROM ALL_AUDIT_LOG), ',
'              '))
);
wwv_flow_imp.component_end;
end;
/
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_shared.append_to_install_script(
 p_id=>wwv_flow_imp.id(34855282644029862853)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'''REPORT_LOG'', ',
'              VT_PID, ',
'              SYSDATE, ',
'              V_ACT_TYPE, ',
'              ACL.GET_CURRENT_USER_PID, ',
'             ''<?xml version="1.0"?> ',
'<ROWSET> ',
'<REPORT_LOG> ',
'<INSERT_DATE><OLD>''||:OLD.INSERT_DATE||''</OLD><NEW>''||:NEW.INSERT_DATE||''</NEW></INSERT_DATE> ',
'<OID><OLD>''||:OLD.OID||''</OLD><NEW>''||:NEW.OID||''</NEW></OID> ',
'<PID_ACL_USER><OLD>''||:OLD.PID_ACL_USER||''</OLD><NEW>''||:NEW.PID_ACL_USER||''</NEW></PID_ACL_USER> ',
'<PID_EMPLOYEE_INSERT_BY><OLD>''||:OLD.PID_EMPLOYEE_INSERT_BY||''</OLD><NEW>''||:NEW.PID_EMPLOYEE_INSERT_BY||''</NEW></PID_EMPLOYEE_INSERT_BY> ',
'<PID_EMPLOYEE_UPDATE_BY><OLD>''||:OLD.PID_EMPLOYEE_UPDATE_BY||''</OLD><NEW>''||:NEW.PID_EMPLOYEE_UPDATE_BY||''</NEW></PID_EMPLOYEE_UPDATE_BY> ',
'<REF_ID><OLD>''||:OLD.REF_ID||''</OLD><NEW>''||:NEW.REF_ID||''</NEW></REF_ID> ',
'<REPORT_DATE><OLD>''||:OLD.REPORT_DATE||''</OLD><NEW>''||:NEW.REPORT_DATE||''</NEW></REPORT_DATE> ',
'<REPORT_NAME><OLD>''||:OLD.REPORT_NAME||''</OLD><NEW>''||:NEW.REPORT_NAME||''</NEW></REPORT_NAME> ',
'<UPDATE_DATE><OLD>''||:OLD.UPDATE_DATE||''</OLD><NEW>''||:NEW.UPDATE_DATE||''</NEW></UPDATE_DATE> ',
'</REPORT_LOG> ',
'</ROWSET>'' ',
'              ); ',
'-- ',
'EXCEPTION ',
'  WHEN OTHERS ',
'  THEN ',
'     RAISE; ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "AUTO_AUDIT_LOG_0087" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "AUTO_USER_GROUP_MY_STOCK" ',
'  after INSERT ',
'  ON MY_USERS   REFERENCING NEW AS NEW OLD AS OLD ',
'  FOR EACH ROW ',
'DECLARe ',
'begin ',
' INSERT INTO USER_GROUP_MY_STOCK (PID, PID_USER, PID_GROUP, IS_ACTIVE, INSERT_BY, INSERT_DATE, UPDATE_BY, UPDATE_DATE) ',
' VALUES (USER_GROUP_MY_STOCK_SEQ.nextval,:new.USER_ID,:new.USER_TYPE,:new.IS_ACTIVE,upper(V(''USER'')),sysdate,upper(V(''USER'')),sysdate); ',
' ',
'EXCEPTION ',
'  WHEN OTHERS ',
'  THEN ',
'     RAISE; ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "AUTO_USER_GROUP_MY_STOCK" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "BI_GALLERY" ',
' before insert on GALLERY for each row',
' begin ',
'  if :NEW.ID is null then ',
'   select GALLERY_SEQ.nextval into :NEW.ID from sys.dual;',
'  end if;',
' end;',
'',
'/',
'',
'',
'ALTER TRIGGER "BI_GALLERY" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "BI_MY_USERS" ',
'  before insert on "MY_USERS"                ',
'  for each row   ',
'begin    ',
'  if :NEW."USER_ID" is null then  ',
'    select "MY_USERS_SEQ".nextval into :NEW."USER_ID" from sys.dual;  ',
'  end if;  ',
'end;  ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "BI_MY_USERS" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "DEPT_TRG1" ',
'              before insert on dept ',
'              for each row ',
'              begin ',
'                  if :new.deptno is null then ',
'                      select dept_seq.nextval into :new.deptno from sys.dual; ',
'                 end if; ',
'              end; ',
'',
'/',
'',
'',
'ALTER TRIGGER "DEPT_TRG1" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "LOGIN_ID_ACL_USER" ',
'BEFORE INSERT OR UPDATE of USER_ID ',
'ON MY_USERS  ',
'REFERENCING NEW AS New OLD AS Old ',
'FOR EACH ROW ',
'DECLARE ',
'BEGIN ',
':NEW.USER_ID := lower(:NEW.USER_ID); ',
'   EXCEPTION ',
'     WHEN OTHERS THEN ',
'       -- Consider logging the error and then re-raise ',
'       RAISE; ',
'END ; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "LOGIN_ID_ACL_USER" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "MENUS_USER_PAGE" ',
'  AFTER INSERT ON MENUS ',
'FOR EACH ROW ',
'BEGIN ',
'INSERT INTO USER_PAGE ',
'(PID, PAGE_ID, DESCRIPTION, APP_ID, STATUS, PAGE_NAME, USER_NAME) ',
'VALUES ',
'(USER_PAGE_SEQ.NEXTVAL, :NEW.OID, :NEW.DESCRIPTION, NULL, ''1'', :NEW.MENU_NAME, V(''APP_USER'')); ',
' ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "MENUS_USER_PAGE" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "MY_USERS_NOTI" ',
'  BEFORE DELETE OR INSERT OR UPDATE ON MY_USERS',
'  FOR EACH ROW',
'BEGIN',
'    DBMS_OUTPUT.PUT(''Old USER_ID= '' || :OLD.USER_ID|| '', '');',
'  DBMS_OUTPUT.PUT(''New USER_ID= '' || :NEW.USER_ID );',
'END;',
'',
'/',
'',
'',
'ALTER TRIGGER "MY_USERS_NOTI" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "MY_USERS_NOTIFICON" ',
'  BEFORE DELETE OR INSERT OR UPDATE ON MY_USERS',
'  FOR EACH ROW',
'BEGIN',
'    DBMS_OUTPUT.PUT(''Old USER_ID= '' || :OLD.USER_ID|| '', '');',
'  DBMS_OUTPUT.PUT(''New USER_ID= '' || :NEW.USER_ID );',
'END;',
'/',
'',
'',
'ALTER TRIGGER "MY_USERS_NOTIFICON" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "OID_PRODUCT_RATING" ',
'BEFORE insert or update ON PRODUCT_RATING ',
'FOR EACH ROW',
'BEGIN',
'if :NEW.OID is null THEN',
'        select PRODUCT_RATING_SEQ.nextval into :new.OID from sys.dual;',
'    END IF;',
'    if inserting then ',
'    :new.CREATE_DATE := localtimestamp; ',
'    :new.CREATE_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user); ',
'  end if; ',
'  :new.UPDATE_DATE := localtimestamp; ',
'  :new.UPDATE_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user); ',
'end OID_PRODUCT_RATING;',
'',
'/',
'',
'',
'ALTER TRIGGER "OID_PRODUCT_RATING" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "OID_PURCHASE_DETALIS" ',
'BEFORE INSERT ON PURCHASE_DETALIS  ',
'FOR EACH ROW ',
'BEGIN ',
'if :NEW.OID is null THEN ',
'        select PURCHASE_DETALIS_SEQ.nextval into :new.OID from sys.dual; ',
'    END IF; ',
'END ; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "OID_PURCHASE_DETALIS" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "OID_SALES_DTLS" ',
'BEFORE insert or update ON SALES_DTLS  ',
'FOR EACH ROW ',
'BEGIN ',
'if :NEW.OID is null THEN ',
'        select SALES_DTL_SEQ.nextval into :new.OID from sys.dual; ',
'    END IF; ',
'    if inserting then  ',
'    :new.CREATE_DATE := localtimestamp;  ',
'    :new.CREATED_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user);  ',
'    :new.IP := owa_util.get_cgi_env(''REMOTE_ADDR''); ',
'  end if;  ',
'  :new.UPDATE_DATE := localtimestamp;  ',
'  :new.UPDATE_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user);  ',
'end OID_SALES_DTLS;',
'',
'/',
'',
'',
'ALTER TRIGGER "OID_SALES_DTLS" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "ORDER_PRODUCT" ',
'         before insert on "ORDER_PRODUCT" ',
'         for each row ',
'       begin ',
'         if :NEW."OID" is null then ',
'        select "ORDER_PRODUCT_SEQ".nextval into :NEW."OID" from sys.dual; ',
'          END IF; ',
'    END;',
'',
'/',
'',
'',
'ALTER TRIGGER "ORDER_PRODUCT" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "PASSWORD_MY_USER" ',
'BEFORE INSERT OR UPDATE of PIN ',
'ON MY_USERS',
'REFERENCING NEW AS New OLD AS Old',
'FOR EACH ROW',
'DECLARE',
'    PASS VARCHAR2(250);',
'BEGIN',
'    PASS := :new.PIN;',
'',
'IF INSERTING',
'  THEN',
'     :NEW.PASSWORD := PASS;',
'  ELSIF UPDATING',
'  THEN',
'     :NEW.PASSWORD := PASS;',
'  END IF;',
'END ;',
'',
'/',
'',
'',
'ALTER TRIGGER "PASSWORD_MY_USER" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "PIN_MY_USER" ',
'BEFORE INSERT OR UPDATE of PIN  ',
'ON MY_USERS ',
'REFERENCING NEW AS New OLD AS Old ',
'FOR EACH ROW ',
'DECLARE ',
'BEGIN ',
':new.PIN:=USER_AUTH_IP.CUSTOM_HASH ( :new.USER_ID, :new.PIN);  ',
' ',
' ',
'IF INSERTING ',
'  THEN ',
'     :NEW.ADDED_DATE := SYSDATE; ',
'  ELSIF UPDATING ',
'  THEN ',
'     :NEW.UPDATE_DATE := SYSDATE; ',
'  END IF; ',
' ',
' ',
'   EXCEPTION ',
'     WHEN OTHERS THEN ',
'       RAISE; ',
'END ; ',
' ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "PIN_MY_USER" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "PRODUCT_USER_ACTIVITY" ',
'  AFTER INSERT OR UPDATE OR DELETE ',
'  ON PRODUCT ',
'   ',
'FOR EACH ROW ',
' ',
'BEGIN ',
' ',
'IF INSERTING THEN ',
'INSERT INTO USER_TABLE_LOG ',
'(LOGE_ID, TABLE_NAME, PRODUCT_ID, ACTION, ADDED_DATE, CREATE_BY, IP, PRODUCT_CODE, PRODUCT_NAME) ',
'VALUES ',
'(USER_TABLE_LOG_SEQ.NEXTVAL, ''PRODUCT'', :NEW.PRODUCT_ID, ''INSERT'', SYSDATE, V(''APP_USER''), owa_util.get_cgi_env(''REMOTE_ADDR''), :NEW.PRODUCT_CODE, :NEW.PRODUCT_NAME); ',
'END IF; ',
' ',
'IF UPDATING THEN ',
'INSERT INTO USER_TABLE_LOG ',
'(LOGE_ID, TABLE_NAME, PRODUCT_ID, ACTION, ADDED_DATE, CREATE_BY, IP, PRODUCT_CODE, PRODUCT_NAME) ',
'VALUES ',
'(USER_TABLE_LOG_SEQ.NEXTVAL, ''PRODUCT'', :OLD.PRODUCT_ID, ''UPDATE'', SYSDATE, V(''APP_USER''), owa_util.get_cgi_env(''REMOTE_ADDR''), :OLD.PRODUCT_CODE, :OLD.PRODUCT_NAME); ',
'END IF; ',
' ',
'IF DELETING THEN ',
'INSERT INTO USER_TABLE_LOG ',
'(LOGE_ID, TABLE_NAME, PRODUCT_ID, ACTION, ADDED_DATE, CREATE_BY, IP, PRODUCT_CODE, PRODUCT_NAME) ',
'VALUES ',
'(USER_TABLE_LOG_SEQ.NEXTVAL, ''PRODUCT'', :OLD.PRODUCT_ID, ''DELETE'', SYSDATE, V(''APP_USER''), owa_util.get_cgi_env(''REMOTE_ADDR''), :OLD.PRODUCT_CODE, :OLD.PRODUCT_NAME); ',
'END IF; ',
' ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "PRODUCT_USER_ACTIVITY" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "PURCHASE_STOCK" ',
'AFTER INSERT OR UPDATE OF SUBMIT   ',
'   ON PURCHASE_DETALIS ',
'FOR EACH ROW ',
'  WHEN (new.SUBMIT = ''1'') DECLARE ',
'a NUMBER; ',
'BEGIN ',
'SELECT max(PRODUCT_ID) INTO a FROM STOCK WHERE (PROOUCT_SIZE =:NEW.PROOUCT_SIZE and PRODUCT_ID =:NEW.PRODUCT_ID); ',
'IF a is not null THEN ',
'UPDATE STOCK ',
'SET STK_QNTY=NVL(STK_QNTY,0)+NVL(:NEW.QTY,0), ',
'IN_QNTY=NVL(IN_QNTY,0)+NVL(:NEW.QTY,0) ',
'WHERE PRODUCT_ID=:NEW.PRODUCT_ID and PROOUCT_SIZE =:NEW.PROOUCT_SIZE; ',
'ELSE ',
'INSERT INTO STOCK(PRODUCT_ID,PROOUCT_SIZE,IN_QNTY,OUT_QNTY,STK_QNTY) ',
'VALUES(:NEW.PRODUCT_ID,:NEW.PROOUCT_SIZE,:NEW.QTY,NULL,:NEW.QTY); ',
'END IF; ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "PURCHASE_STOCK" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "REPORT_LOG_DT" ',
'  BEFORE INSERT OR UPDATE ',
'  ON REPORT_LOG ',
'  REFERENCING NEW AS NEW OLD AS OLD ',
'  FOR EACH ROW ',
'BEGIN ',
':NEW.REPORTING_DATE:=TRUNC(:NEW.REPORT_DATE); ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "REPORT_LOG_DT" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "RETERN_PURCHASE_STOCK" ',
'  AFTER UPDATE OR DELETE  ',
'  ON PURCHASE_DETALIS ',
'FOR EACH ROW ',
' ',
'BEGIN ',
' ',
' ',
'IF UPDATING AND :OLD.SUBMIT = 1 THEN ',
'INSERT INTO RETERN_PURCHASE_DETALIS ',
'(OID, VOUCHER_NO, PRODUCT_ID, ITEM_NAME, PROOUCT_SIZE, CPU, QTY, TOTAL, SUBMIT, Created_By, ACTION, CREATE_DATE) ',
'VALUES ',
'(RETERN_PURCHASE_STOCK.NEXTVAL, :OLD.VOUCHER_NO,  :OLD.PRODUCT_ID, :OLD.ITEM_NAME,  :OLD.PROOUCT_SIZE,  :OLD.CPU, :NEW.RETERN_PRODUCT, :NEW.REFUND_TO_CUSTOMER, :OLD.SUBMIT, V(''APP_USER''), ''UPDATE'', SYSDATE); ',
'END IF; ',
' ',
' ',
'IF DELETING AND :OLD.SUBMIT = 1 THEN ',
'INSERT INTO RETERN_PURCHASE_DETALIS ',
'(OID, VOUCHER_NO, PRODUCT_ID, ITEM_NAME, PROOUCT_SIZE, CPU, QTY, TOTAL, SUBMIT, Created_By, ACTION, CREATE_DATE) ',
'VALUES ',
'(RETERN_PURCHASE_STOCK.NEXTVAL, :OLD.VOUCHER_NO, :OLD.PRODUCT_ID, :OLD.ITEM_NAME,  :OLD.PROOUCT_SIZE,  :OLD.CPU, :OLD.QTY, :OLD.TOTAL, :OLD.SUBMIT, V(''APP_USER''), ''DELETE'', SYSDATE); ',
'END IF; ',
'END; ',
'',
'/',
'',
'',
'ALTER TRIGGER "RETERN_PURCHASE_STOCK" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "SALES_STOCK" ',
'AFTER INSERT OR UPDATE OF SUBMIT   ',
'ON SALES_DTLS ',
'FOR EACH ROW ',
'   WHEN (new.SUBMIT = ''1'') DECLARE ',
'A NUMBER; ',
'BEGIN ',
'SELECT STK_QNTY INTO a from STOCK WHERE PRODUCT_ID=:NEW.PRODUCT_ID and PROOUCT_SIZE =:NEW.PROOUCT_SIZE; ',
'if :NEW.QTY <= a then ',
'UPDATE STOCK ',
'SET STK_QNTY=NVL(STK_QNTY,0)-NVL(:NEW.QTY,0), ',
'OUT_QNTY=NVL(OUT_QNTY,0)+NVL(:NEW.QTY,0) ',
'WHERE PRODUCT_ID=:NEW.PRODUCT_ID and PROOUCT_SIZE =:NEW.PROOUCT_SIZE; ',
'  ELSE ',
unistr('  raise_application_error(-20111,''\0986\09AA\09A8\09BE\09B0 \09B8\09CD\099F\0995 \0995\09AE''); '),
'  end if; ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "SALES_STOCK" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "SLIDESHOW_IMG" ',
'  before insert on "SLIDESHOW_IMG"                ',
'  for each row   ',
'begin    ',
'  if :NEW."OID" is null then  ',
'    select "SLIDESHOW_IMG_SEQ".nextval into :NEW."OID" from sys.dual;  ',
'  end if;  ',
'end; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "SLIDESHOW_IMG" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT" ',
'         before insert on "STUDENT" ',
'         for each row ',
'       begin ',
'         if :NEW."STUDENT_ID" is null then ',
'        select "STUDENT_SEQ".nextval into :NEW."STUDENT_ID" from sys.dual; ',
'          END IF; ',
'    END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "STUDENT" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "USER_T" ',
'BEFORE INSERT OR UPDATE ON POS_USER ',
'FOR EACH ROW ',
'BEGIN ',
'IF :NEW.PASSWORD IS NOT NULL THEN ',
':NEW.PASSWORD:=CUSTOM_HASH(UPPER(:NEW.USER_NAME),(:NEW.PASSWORD)); ',
'END IF; ',
'IF INSERTING THEN ',
'IF :NEW.USER_ID IS NULL THEN ',
'SELECT NVL(MAX(USER_ID)+1,1) INTO :NEW.USER_ID FROM POS_USER; ',
'END IF; ',
'END IF; ',
'END; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "USER_T" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "USER_TABLE_DETELS" ',
'  before insert or update on MY_USERS ',
'  for each row ',
'begin ',
'  if inserting then ',
'    :new.ADDED_DATE := localtimestamp; ',
'    :new.CREATE_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user); ',
'  end if; ',
'  :new.UPDATE_DATE := localtimestamp; ',
'  :new.UPDATE_BY := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user); ',
'end USER_TABLE_DETELS;',
'',
'/',
'',
'',
'ALTER TRIGGER "USER_TABLE_DETELS" ENABLE;',
'',
'CREATE OR REPLACE EDITIONABLE TRIGGER "USER_UPDATE_LOGS" ',
'  before insert or update on USERS_LOG  ',
'  for each row  ',
'begin  ',
'  if :new.LOG_ID is null then  ',
'    :new.LOG_ID := to_number(sys_guid(), ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');  ',
'  end if;  ',
'  if inserting then  ',
'    :new.created := localtimestamp;  ',
'    :new.created_by := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user);  ',
'  end if;  ',
'  :new.updated := localtimestamp;  ',
'  :new.updated_by := nvl(sys_context(''APEX$SESSION'',''APP_USER''),user);  ',
'end user_update_logs; ',
' ',
'',
'/',
'',
'',
'ALTER TRIGGER "USER_UPDATE_LOGS" ENABLE;',
'',
''))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855282710156862856)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ACL_USER_GROUP'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855282973239862856)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ALL_AUDIT_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855283185611862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ALL_LANGUAGES'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855283391047862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'APPS_NAME'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855283549049862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'APX$ERR$EMP$679256'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855283718290862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ASSET'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855283918800862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'BRAND'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855284105202862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'CATEGORY'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855284381220862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'COLOR'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855284549496862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'COUNTRY'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855284736082862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'COURT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855284992675862857)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'CUSTOMER'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855285189634862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'DEPT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855285388632862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'DISTRICT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855285538138862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'DIVISION'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855285723056862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'DOB'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855285900988862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'EMP'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855286188425862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'EXPORT_CLOB'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855286328463862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'E_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855286573881862858)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'GALLERY'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855286781161862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'GROUP_NAME'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855286963451862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'HTMLDB_PLAN_TABLE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855287132327862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'IMAGES'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855287308633862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'INFOFOLLOWUP'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855287592627862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'IS_ACTIVATE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855287725096862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ITEM_SIZE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855287996834862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'LIKE_TABLE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855288115140862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MENUS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855288328468862859)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MENUS_ACCESS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855288503632862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MY_FILE_TABLE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855288723970862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MY_IMPORTENT_CODE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855288942299862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MY_SHOP_NAME'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855289161459862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'MY_USERS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855289386931862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'NOTIFICATION'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855289543333862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'NOTI_CATEGORY'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855289794590862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ORDER_PRODUCT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855289924883862860)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'POST_BLOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855290174486862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'POS_USER'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855290316299862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PRODUCT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855290545048862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PRODUCT_DETELS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855290799491862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PRODUCT_PRICE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855290992095862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PRODUCT_RATING'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp.component_end;
end;
/
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855291199664862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PURCHASE_DETALIS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855291398932862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PURCHASE_MASTER'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855291589266862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'REPORT_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855291712002862861)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'REPORT_VIEW_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855291983727862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'RETERN_PURCHASE_DETALIS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855292158778862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SALES_DTLS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855292322304862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SALES_MST'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855292556163862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SALES_ORDER'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855292763028862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SLIDESHOW_IMG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855292966162862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'STOCK'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855293141365862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'STUDENT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855293363282862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SUPPLIER'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855293515603862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SURETY_ACCOUNT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855293760743862862)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'TAPEX_WORKSPACE_ACCESS_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855293916824862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'TAPEX_WORKSPACE_ACTIVITY_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855294112182862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'TAST_LOCTION'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855294300068862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'TEST'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855294546235862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'THANAUPAZILA'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855294702493862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'TREE_MENU'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855294950534862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'UNIT'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855295179736862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USERS_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855295397737862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_GROUP'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855295562487862863)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_GROUP_MY_STOCK'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855295720552862864)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_GROUP_PAGE_ACCESS'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855295922306862864)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_LOC'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855296164273862864)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_LOG_WEB'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855296320556862864)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_PAGE'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(34855296595401862864)
,p_script_id=>wwv_flow_imp.id(34855282644029862853)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'USER_TABLE_LOG'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_updated_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
,p_created_by=>'JABER0181@GMAIL.COM'
,p_created_on=>to_date('20220128125253','YYYYMMDDHH24MISS')
);
wwv_flow_imp.component_end;
end;
/
