prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/all_test_page_menus.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/files/apex_data_pkg_acl_user_group_262787_zip.sql
@@application/shared_components/files/apex_data_pkg_apps_name_283075_zip.sql
@@application/shared_components/files/apex_data_pkg_brand_951805_zip.sql
@@application/shared_components/files/apex_data_pkg_category_831078_zip.sql
@@application/shared_components/files/apex_data_pkg_color_312569_zip.sql
@@application/shared_components/files/apex_data_pkg_country_765899_zip.sql
@@application/shared_components/files/apex_data_pkg_court_735788_zip.sql
@@application/shared_components/files/apex_data_pkg_customer_640687_zip.sql
@@application/shared_components/files/apex_data_pkg_dept_209411_zip.sql
@@application/shared_components/files/apex_data_pkg_district_145192_zip.sql
@@application/shared_components/files/apex_data_pkg_division_886788_zip.sql
@@application/shared_components/files/apex_data_pkg_emp_679256_zip.sql
@@application/shared_components/files/apex_data_pkg_e_log_222244_zip.sql
@@application/shared_components/files/apex_data_pkg_group_name_667750_zip.sql
@@application/shared_components/files/apex_data_pkg_is_activate_65912_zip.sql
@@application/shared_components/files/apex_data_pkg_item_size_330750_zip.sql
@@application/shared_components/files/apex_data_pkg_like_table_690627_zip.sql
@@application/shared_components/files/apex_data_pkg_menus_550003_zip.sql
@@application/shared_components/files/apex_data_pkg_my_importent_code_725472_zip.sql
@@application/shared_components/files/apex_data_pkg_my_shop_name_347177_zip.sql
@@application/shared_components/files/apex_data_pkg_my_users_757396_zip.sql
@@application/shared_components/files/apex_data_pkg_notification_311973_zip.sql
@@application/shared_components/files/apex_data_pkg_noti_category_788951_zip.sql
@@application/shared_components/files/apex_data_pkg_order_product_45290_zip.sql
@@application/shared_components/files/apex_data_pkg_product_880484_zip.sql
@@application/shared_components/files/apex_data_pkg_product_detels_365454_zip.sql
@@application/shared_components/files/apex_data_pkg_product_price_778133_zip.sql
@@application/shared_components/files/apex_data_pkg_product_rating_603618_zip.sql
@@application/shared_components/files/apex_data_pkg_purchase_detalis_285786_zip.sql
@@application/shared_components/files/apex_data_pkg_purchase_master_490861_zip.sql
@@application/shared_components/files/apex_data_pkg_retern_purchase_detalis_193150_zip.sql
@@application/shared_components/files/apex_data_pkg_sales_dtls_558802_zip.sql
@@application/shared_components/files/apex_data_pkg_sales_mst_560609_zip.sql
@@application/shared_components/files/apex_data_pkg_sales_order_654219_zip.sql
@@application/shared_components/files/apex_data_pkg_slideshow_img_929588_zip.sql
@@application/shared_components/files/apex_data_pkg_stock_815798_zip.sql
@@application/shared_components/files/apex_data_pkg_student_272236_zip.sql
@@application/shared_components/files/apex_data_pkg_supplier_490536_zip.sql
@@application/shared_components/files/apex_data_pkg_tapex_workspace_access_l_675736_zip.sql
@@application/shared_components/files/apex_data_pkg_test_892936_zip.sql
@@application/shared_components/files/apex_data_pkg_thanaupazila_492763_zip.sql
@@application/shared_components/files/apex_data_pkg_users_log_173493_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_197503_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_my_stock_726944_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_page_access_859870_zip.sql
@@application/shared_components/files/apex_data_pkg_user_loc_180049_zip.sql
@@application/shared_components/files/apex_data_pkg_user_page_206830_zip.sql
@@application/shared_components/files/jquery_elevatezoom_3_0_8_min_js.sql
@@application/shared_components/files/jquery_magnific_popup_js.sql
@@application/shared_components/files/magnific_popup_css.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/06_jpg.sql
@@application/shared_components/files/05_jpg.sql
@@application/shared_components/files/04_jpg.sql
@@application/shared_components/files/03_jpg.sql
@@application/shared_components/files/02_jpg.sql
@@application/shared_components/files/01_jpg.sql
@@application/shared_components/files/spin_min_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/ap_relogin.sql
@@application/shared_components/logic/application_processes/“add_employee.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/instant_search_report.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/mobile_view.sql
@@application/shared_components/user_interface/templates/report/standard_2_instant_search.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/security/authentications/test_user_login.sql
@@application/shared_components/security/authentications/test_custom_auth.sql
@@application/shared_components/plugins/dynamic_action/apex_items_with_buttons.sql
@@application/shared_components/plugins/dynamic_action/me_vmorneau_animapex.sql
@@application/shared_components/plugins/dynamic_action/com_uk_explorer_dlar.sql
@@application/shared_components/plugins/dynamic_action/print_region_to_pdf_v_2_0.sql
@@application/shared_components/plugins/item_type/be_ctb_select2.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00092.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_all_test_page_script.sql
@@application/deployment/install/install_all_test_page_data_script.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
