prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@workspace/credentials/google.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/dynamic_menu_list.sql
@@application/shared_components/files/xlsx_full_min_js_download.sql
@@application/shared_components/files/bensound_adventure_mp3.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/06_jpg.sql
@@application/shared_components/files/logo_png.sql
@@application/shared_components/files/apex_data_pkg_apps_name_283075_zip.sql
@@application/shared_components/files/apex_data_pkg_category_831078_zip.sql
@@application/shared_components/files/apex_data_pkg_country_765899_zip.sql
@@application/shared_components/files/apex_data_pkg_court_735788_zip.sql
@@application/shared_components/files/apex_data_pkg_dept_209411_zip.sql
@@application/shared_components/files/apex_data_pkg_district_145192_zip.sql
@@application/shared_components/files/apex_data_pkg_division_886788_zip.sql
@@application/shared_components/files/apex_data_pkg_emp_679256_zip.sql
@@application/shared_components/files/apex_data_pkg_e_log_222244_zip.sql
@@application/shared_components/files/apex_data_pkg_group_name_667750_zip.sql
@@application/shared_components/files/apex_data_pkg_is_activate_65912_zip.sql
@@application/shared_components/files/apex_data_pkg_like_table_690627_zip.sql
@@application/shared_components/files/apex_data_pkg_menus_550003_zip.sql
@@application/shared_components/files/apex_data_pkg_my_file_table_347327_zip.sql
@@application/shared_components/files/apex_data_pkg_my_users_757396_zip.sql
@@application/shared_components/files/apex_data_pkg_order_product_45290_zip.sql
@@application/shared_components/files/apex_data_pkg_product_880484_zip.sql
@@application/shared_components/files/apex_data_pkg_product_detels_365454_zip.sql
@@application/shared_components/files/apex_data_pkg_product_price_778133_zip.sql
@@application/shared_components/files/apex_data_pkg_product_rating_603618_zip.sql
@@application/shared_components/files/apex_data_pkg_purchase_master_490861_zip.sql
@@application/shared_components/files/apex_data_pkg_sales_dtls_558802_zip.sql
@@application/shared_components/files/apex_data_pkg_sales_mst_560609_zip.sql
@@application/shared_components/files/apex_data_pkg_slideshow_img_929588_zip.sql
@@application/shared_components/files/apex_data_pkg_student_272236_zip.sql
@@application/shared_components/files/apex_data_pkg_thanaupazila_492763_zip.sql
@@application/shared_components/files/apex_data_pkg_unit_530723_zip.sql
@@application/shared_components/files/apex_data_pkg_users_log_173493_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_197503_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_my_stock_726944_zip.sql
@@application/shared_components/files/apex_data_pkg_user_group_page_access_859870_zip.sql
@@application/shared_components/files/apex_data_pkg_user_page_206830_zip.sql
@@application/shared_components/files/apex_data_pkg_user_table_log_542547_zip.sql
@@application/shared_components/files/01_jpg.sql
@@application/shared_components/files/02_jpg.sql
@@application/shared_components/files/03_jpg.sql
@@application/shared_components/files/04_jpg.sql
@@application/shared_components/files/05_jpg.sql
@@application/shared_components/files/image_elevatezoom_js_file_jquery_elevatezoom_3_0_8_min_js.sql
@@application/shared_components/files/jquery_magnific_popup_js.sql
@@application/shared_components/files/jquery_elevatezoom_3_0_8_min_js.sql
@@application/shared_components/files/magnific_popup_css.sql
@@application/shared_components/files/apex_data_pkg_all_languages_148155_zip.sql
@@application/shared_components/files/apex_data_pkg_post_blog_952950_zip.sql
@@application/shared_components/files/apex_data_pkg_purchase_detalis_285786_zip.sql
@@application/shared_components/files/app_95068_logo_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/spin_min_js.sql
@@application/shared_components/files/pp_js.sql
@@application/shared_components/files/ga_js.sql
@@application/shared_components/files/autocorrect_common_chunk_js.sql
@@application/shared_components/files/autocorrect_common_chunk_min_js.sql
@@application/shared_components/files/pp_min_js.sql
@@application/shared_components/files/iphone_xr_mp3.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/show_app_msg.sql
@@application/shared_components/logic/application_processes/download_blob.sql
@@application/shared_components/logic/application_processes/get_emp_data.sql
@@application/shared_components/logic/application_items/app_msg.sql
@@application/shared_components/logic/application_items/file_id.sql
@@application/shared_components/logic/application_computations/p0_order_id.sql
@@application/shared_components/logic/application_computations/p2_like.sql
@@application/shared_components/logic/application_computations/p2_unlike.sql
@@application/shared_components/logic/application_computations/p0_order_product_oid.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/category.sql
@@application/shared_components/user_interface/lovs/group_name.sql
@@application/shared_components/user_interface/lovs/item_size.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/product_name.sql
@@application/shared_components/user_interface/lovs/status.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/navigation_bar_2.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/material_cards_region_plugin.sql
@@application/shared_components/user_interface/templates/report/product_card_ui_design.sql
@@application/shared_components/user_interface/templates/report/templates_1.sql
@@application/shared_components/user_interface/templates/report/templates_2.sql
@@application/shared_components/user_interface/templates/report/instant_search_standard_2.sql
@@application/shared_components/user_interface/templates/report/responsive.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/security/authentications/custom_auth.sql
@@application/shared_components/security/authentications/google.sql
@@application/shared_components/plugins/dynamic_action/apex_profiler.sql
@@application/shared_components/plugins/item_type/be_ctb_select2.sql
@@application/shared_components/plugins/dynamic_action/apex_items_with_buttons.sql
@@application/shared_components/plugins/dynamic_action/ca_maximet_apexdialogopen.sql
@@application/shared_components/plugins/dynamic_action/me_vmorneau_animapex.sql
@@application/shared_components/plugins/dynamic_action/print_region_to_pdf_v_2_0.sql
@@application/shared_components/plugins/dynamic_action/highlight_text_based_on_voice_input.sql
@@application/shared_components/plugins/item_type/si_abakus_searchnavigationmenu.sql
@@application/shared_components/plugins/dynamic_action/apex_unleash_richtexteditor.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00076.sql
@@application/pages/page_00078.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00085.sql
@@application/pages/page_00087.sql
@@application/pages/page_00089.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_demo_application_table.sql
@@application/deployment/install/install_demo_application_fun_ind_pac_seq_tri.sql
@@application/deployment/install/install_demo_app_data.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
