prompt --application/pages/page_00000
begin
--   Manifest
--     PAGE: 00000
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>13501875225360637847
,p_default_application_id=>78259
,p_default_id_offset=>0
,p_default_owner=>'FLMPJGAZDYSOYO'
);
wwv_flow_imp_page.create_page(
 p_id=>0
,p_user_interface_id=>wwv_flow_imp.id(33247297241416359140)
,p_name=>'Global Page - Desktop'
,p_step_title=>'Global Page - Desktop'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'D'
,p_page_component_map=>'14'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20211127200248'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11647934188614987405)
,p_plug_name=>'Internet Check'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(33247185261157359055)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'AFTER_HEADER'
,p_plug_item_display_point=>'BELOW'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<html>',
'		<head>',
'		<title>Page Title</title>',
'		<link href="https://cdnjs.cloudflare.com/ajax/libs/offline-js/0.7.19/themes/offline-theme-slide.min.css" rel="stylesheet" type="text/css"></link>',
'		<link href="https://cdnjs.cloudflare.com/ajax/libs/offline-js/0.7.19/themes/offline-language-english.min.css" rel="stylesheet"></link>',
'		</head>',
'		<script src="https://cdnjs.cloudflare.com/ajax/libs/offline-js/0.7.19/offline.min.js"></script>',
'		<script>',
'		Offline.options = {checks: {xhr: {url: ''#APP_IMAGES#check-internet-connection-javascript.gif''}}};',
'		</script>',
'		<body>',
'		</body>',
'	</html>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(25675205672085908902)
,p_plug_name=>'Police'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(33247185261157359055)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'AFTER_HEADER'
,p_plug_item_display_point=>'BELOW'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<style>',
'body{',
'    background-size: cover;',
'    font-family: SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'}',
'',
'.t-Form-fieldContainer .t-Form-label {',
'    font-size: 18px;',
'}',
'',
'.t-Button {',
'    font-size: 1.6rem;',
'    line-height: 1.6rem;',
'    padding: .8rem 1.2rem;',
'    font-weight: 400;',
'}',
'',
'',
'.t-Footer {',
'    display: none;',
'}',
'',
'.ui-corner-all, .ui-corner-bottom, .ui-corner-right, .ui-corner-br {',
'    border-bottom-right-radius: 10px !important;',
'}',
'',
'.ui-corner-all, .ui-corner-bottom, .ui-corner-left, .ui-corner-bl {',
'    border-bottom-left-radius: 10px !important;',
'}',
'',
'.borderless-region a {',
'    text-decoration: none !important;',
'}',
'',
'.UID_view{',
'font-size:8px;',
'color:#a9a9a9;',
'}',
'',
'div.tSC {',
'    /*background-color: #F0F0F0;',
'    border-left: 1px solid #999999;',
'    border-right: 1px solid #999999;',
'    padding: 4px 10px 0;*/',
'    text-align: center;',
'}',
'',
'.rpt_report_logid {',
'    font-family: arial;',
'    font-size: 10px;',
'    padding: 3px;',
'    text-align: right;',
'}',
'.rpt_goponio {',
'    ',
'    color:#333333;',
'}',
'.rpt_report_head {',
'    font-size: 14px;',
'    font-weight:bold;',
'    text-align:center;',
'}',
'.rpt_police_date {',
'    text-align: left;',
'     ',
'}',
'',
'.a-IRR {',
'    border-radius: 2px;',
'    overflow: hidden;',
'    font-size: 1.6rem;',
'}',
'',
'table{',
'width:100%;',
'',
'    border-collapse: collapse;',
'}',
'',
'#superlov-fetch-results .superlov-table .ui-widget .ui-widget-content .ui-corner-all',
'{',
'   width:1000px;',
'font-family: SolaimanLipi;',
'',
'',
'}',
'table.superlov-table  {',
'    font-family: SolaimanLipi;',
'}',
'',
'',
'.apexir_WORKSHEET_DATA td {',
'    border-bottom: 1px solid #AAAAAA;',
'    border-right: 1px solid #AAAAAA;',
'   font: 14px/14px SolaimanLipi,Times New Roman;',
'    ',
'    padding:5px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'}',
'',
'.report-standard td.data {',
'    border-right: 1px solid #DDDDDD;',
'font: 14px/14px SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    ',
'}',
'',
'',
'input[type="text"]{',
'    font-size: 18px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    width: auto;',
'    text-align:left;',
'    border-radius: 5px;',
'}',
'',
'',
'input[type="password"]{',
'    font-size: 20px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    text-align:left !important;',
'    border-radius: 5px;',
'}',
'',
'textarea{',
'    font-size: 18px;',
'    padding:3px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    width: 242px;',
'    color:#003399;',
'}',
'select{',
'    font-size: 18px;',
'    padding:3px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    text-align:left !important;',
'    width: 250px;',
'    color:#003399;',
'}',
'',
'.borderless-region .bl-body {',
'    font: 16px/16px SolaimanLipi,Arial,sans-serif;',
'}',
'',
'',
'div#breadcrumb_container ul li a {',
'    color: #338888;',
'    ',
'}',
'',
'',
'.ui-accordion-icons .ui-accordion-header a {',
'    font-family: SolaimanLipi;',
'    font-size: 16px;',
'}',
'',
'a.optional-w-help, a.required-w-help {',
'   ',
'    font-size: 16px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    font-weight: normal;',
'    white-space: wrap;',
'}',
'',
'',
'div#breadcrumb_container ul li a {',
'font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'font-size:16px;',
'}',
'',
'.optional-w-help {',
'   ',
'    white-space: wrap;',
'}',
'',
'.vertical-sidebar-list .active a, .vertical-sidebar-list .active a:hover {',
'     font-size: 16px;',
'font: bold 16px/16px SolaimanLipi,Times New Roman !important;',
'}',
'',
'',
'.vertical-sidebar-list a {',
'    ',
'    font-size: 16px;',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    ',
'}',
'',
'.t1PopupBody a {',
'    border-bottom: 1px solid #EE88EE;',
'    display: block;',
'    font: 16px/18px SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'   ',
'}',
'',
'.ui-widget {',
'font-family:SolaimanLipi, Arial,sans-serif;',
'font-size:16px;',
'}',
'',
'',
'.borderless-region .bl-title {',
'font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'font-size:16px;',
'font-weight:bold;',
'}',
'',
'#apexir_CONTROL_PANEL {',
'    width: auto;',
'}',
'',
'.apexir_WORKSHEET_DATA th div {',
'     font: bold 14px/16px SolaimanLipi,Times New Roman;',
'    font-size: 16px;',
'',
'}',
'',
'.worksheet_detail th, .worksheet_detail td {',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    font-size: 16px;',
'}',
'',
'',
'.worksheet_detail th {',
'    width:35%;',
'}',
'',
'td.data {',
'    ',
'    text-align: left;',
'}',
'',
'.rounded-corner-region-wizard {',
'    float: left;',
'    max-width: 600px;',
'    min-width: 330px;',
'}',
'ul.dhtmlTree li {',
'    ',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    font-size: 16px;',
'}',
'',
'.rounded-corner-region .rc-title, .rounded-corner-region-alt .rc-title, .rounded-corner-region-wizard .rc-title {',
'    font-family:SolaimanLipi,Times New Roman,BlinkMacSystemFont,Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;',
'    font-size: 18px;',
'}',
'',
'',
'.rounded-corner-region .rc-body .rc-body-r, .rounded-corner-region-wizard .rc-body .rc-body-r, .rounded-corner-region-blank-white .rc-body .rc-body-r {',
'    font-size: 14px;',
'}',
'',
'.report-standard th.header, .report-borderless th.header {',
'    background: none repeat scroll 0 0 transparent;',
'    font: bold 14px/14px SolaimanLipi,Times New Roman;',
'    ',
'}',
'',
'.t1PopupBody a {',
'    border-bottom: 1px solid #999999;',
'    color: #005500;',
'    font: 16px/18px SolaimanLipi,Times New Roman;',
'}',
'.t-Report-cell, .t-Report-colHead {',
'    font-size: 1.6rem;',
'}',
'',
'.t-Region-headerItems--title {',
'    padding: 0.6rem;',
'    font-size: 2.0rem;',
'}',
'',
'.button {',
'    background-color: #4CAF50; /* Green */',
'    border: none;',
'    color: white;',
'    padding: 5px;',
'    text-align: center;',
'    text-decoration: none;',
'    display: inline-block;',
'    font-size: 15px;',
'    margin: 4px 2px;',
'    -webkit-transition-duration: 0.4s; /* Safari */',
'    transition-duration: 0.4s;',
'    cursor: pointer;',
'    width:10%;',
'    border-radius: 5px;',
'}',
'',
'.button1 {',
'    background-color: white;',
'    color: black;',
'    border: 2px solid #325930;',
'}',
'.button1:hover {',
'    background-color: #325930;',
'    color: white;',
'}',
'',
'',
'.button3 {',
'    background-color: white;',
'    color: black;',
'    border: 2px solid #f44336;',
'}',
'',
'.button3:hover {',
'    background-color: #f44336;',
'    color: white;',
'}',
'',
'.button4 {',
'    background-color: white;',
'    color: black;',
'    border: 2px solid #325930;',
'}',
'',
'.button4:hover {',
'    background-color: #325930;',
'    color: white;',
'}',
'.button5 {',
'    background-color: white;',
'    color: black;',
'    border: 2px solid #000000;',
'}',
'',
'.button5:hover {',
'    background-color: #81BB5F;',
'    color: white;',
'}',
'',
'</style>',
'',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(25675205741433908903)
,p_plug_name=>'Report'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(33247185261157359055)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'AFTER_HEADER'
,p_plug_item_display_point=>'BELOW'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<script type="text/javascript">',
'function PRINTPAGE(){',
'           $(''#R6639725547831712'').hide();',
'           $(''#report_header_comon'').hide();',
'           $(''#uBreadcrumbsBG'').hide();',
'           $(''#uBreadcrumbs'').hide();',
'           $(''#apexir_TOOLBAR'').hide();',
'           $(''#header'').hide();',
'           $(''#tabs'').hide();',
'           $(''#topbar'').hide();',
'           $(''.tSC'').hide();',
'           $(''.tSF'').hide();',
'           $(''.t-Body-nav'').hide();',
'           $(''.fg-toolbar'').hide();',
'           $(''#report_header_comon'').show();         ',
'           $(''#print_search'').hide();',
'           $(''.t-Header-nav'').hide();',
'           $(''.t-Header-branding'').hide();',
'           $(''.t-Footer-body'').hide();',
'           $(''.t-Breadcrumb'').hide();',
'           $(''#t_Body_content_offset'').hide();',
'           $(''#CIBIT10'').hide();',
'           ',
'           ',
'                      ',
'                      ',
'           ',
'            window.print();',
'',
'',
'           $(''#print_search'').show();',
'           $(''#report_header_comon'').hide();',
'           $(''#apexir_TOOLBAR'').show();',
'           $(''#header'').show();',
'           $(''#tabs'').show();',
'           $(''#topbar'').show();',
'',
'           $(''.tSC'').show();',
'           $(''.tSF'').show();',
'           $(''.fg-toolbar'').show();',
'           $(''#R6639725547831712'').show();',
'          $(''#uBreadcrumbsBG'').show();',
'          $(''#uHeader'').show();',
'          $(''#uBreadcrumbs'').show();',
'          $(''.common-hide-region'').show();',
'           $(''#common-hide-region'').show();',
'         ',
'         ',
'         ',
'       };',
'  </script>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp.component_end;
end;
/
