prompt --application/pages/page_00031
begin
--   Manifest
--     PAGE: 00031
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>13501875225360637847
,p_default_application_id=>78259
,p_default_id_offset=>0
,p_default_owner=>'FLMPJGAZDYSOYO'
);
wwv_flow_imp_page.create_page(
 p_id=>31
,p_user_interface_id=>wwv_flow_imp.id(33247297241416359140)
,p_name=>'Social-Media-App-UI-Design'
,p_alias=>'SOCIAL-MEDIA-APP-UI-DESIGN'
,p_step_title=>'Social-Media-App-UI-Design'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'11'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20210611135633'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(10728695965972090217)
,p_plug_name=>'Social-Media-App-UI-Design'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(33247212693934359074)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="post-body entry-content" id="post-body-8988753844314926072" itemprop="description articleBody">',
'',
'<br>',
'1. Create a classic report by your query<br>',
'2. Take a item for input search content<br>',
'3. Goto Shared Components &gt;&gt; Templates &gt;&gt;Copy Report (Type)/Standard (Name) with diffrent&nbsp; &nbsp; &nbsp; &nbsp;name like&nbsp; Standard2<br>',
'4. Goto Standard2 &gt;&gt; After Column Heading &gt;&gt; &lt;/thead&gt; &lt;tbody id="id" &gt;&nbsp; and save<br>',
'5. Goto Report Attributes &gt;&gt; Appearance &gt;&gt;Template &gt;&gt; Standard2<br>',
'6. Copy the code into Page &gt;&gt; Execute when Page Loads<br>',
'<br>',
'<span style="color: blue;">(Change item name and id)</span><br>',
'<br>',
'&nbsp; <span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp;$(document).ready(function(){</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; $("#<span style="color: blue;">P9_SEARCH</span>").on("keyup", function() {</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; &nbsp; var value = $(this).val().toLowerCase();</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; &nbsp; $("#<span style="color: blue;">id </span>tr").filter(function() {</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; &nbsp;$(this).toggle($(this).text().toLowerCase().indexOf(value) &gt; -1)</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; &nbsp; });</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">&nbsp; });</span><br>',
'<span style="font-family: &quot;courier new&quot; , &quot;courier&quot; , monospace;">});</span><br>',
'<br>',
'Then Enjoy',
'<div style="clear: both;"></div>',
'</div>',
'',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(36149347939990385920)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-Region--noPadding:t-Region--removeHeader:t-Region--noBorder:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(33247212693934359074)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html>',
'<html lang="en">',
'<style>',
'* {',
'  margin: 0;',
'  padding: 0;',
'  box-sizing: border-box;',
'}',
'',
'body {',
'  font-family: ''Montserrat'';',
'  background: #242C39;',
'  color: #fff;',
'}',
'',
'.live {',
'  height: 120px;',
'  width: 100%;',
'  display: flex;',
'  justify-content: space-between;',
'  overflow-x: scroll;',
'  padding: 30px 0 0 20px;',
'  margin-bottom: 20px;',
'}',
'',
'.live .person {',
'  position: relative;',
'  margin-right: 30px;',
'  text-align: center;',
'}',
'',
'.live .profile-pic {',
'  position: relative;',
'  background-position: 50%;',
'  background-size: cover;',
'  height: 40px;',
'  width: 40px;',
'  border-radius: 50%;',
'}',
'',
'.live .person:nth-child(1) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'');}',
'.live .person:nth-child(2) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80'');}',
'.live .person:nth-child(3) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1506919258185-6078bba55d2a?ixlib=rb-1.2.1&auto=format&fit=crop&w=815&q=80'');}',
'.live .person:nth-child(4) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'');}',
'.live .person:nth-child(5) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1505503693641-1926193e8d57?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80'');}',
'.live .person:nth-child(6) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1484588168347-9d835bb09939?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80'');}',
'.live .person:nth-child(7) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80./img/07.jpg'');}',
'.live .person:nth-child(8) .profile-pic {background-image: url(''https://images.unsplash.com/photo-1450297350677-623de575f31c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80'');}',
'',
'',
'.live .profile-pic::before {',
'  content: '''';',
'  display: inline-block;',
'  border: 3px solid #454D5A;',
'  padding: 24px;',
'  border-radius: 50%;',
'  position: absolute;',
'  top: 50%;',
'  left: 50%;',
'  transform: translate(-50%, -50%);',
'}',
'',
'.live .person .name {',
'  font-size: 12px;',
'  padding-top: 20px;',
'}',
'',
'.live-active .profile-pic:before {',
'  border-color: #FFDF3B !important;',
'}',
'',
'.live-active span {',
'  background: #FFDF3B;',
'  color: #000;',
'  width: 50px;',
'  display: inline-block;',
'  font-size: 10px;',
'  border-radius: 50px;',
'  padding: 2px 0;',
'  font-weight: 600;',
'',
'  position: absolute;',
'  top: 50%;',
'  left: 50%;',
'  transform: translate(-50%, -50%);',
'}',
'',
'.live-active i {',
'  padding-right: 3px;',
'}',
'',
'.newsfeed {',
'  padding: 0 20px;',
'}',
'',
'.card {',
'  width: 100%;',
'  height: 100%;',
'  background: #242C39;',
'  box-shadow: 0 0 12px 2px rgba(0, 0, 0, .5);',
'  margin-bottom: 20px;',
'  border-radius: 10px;',
'  font-size: 14px;',
'}',
'',
'.card .picture {',
'  background-image: url(''https://images.unsplash.com/photo-1508166785545-c2dd4c113c66?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'');',
'  background-position: 50%;',
'  background-size: cover;',
'  height: 200px;',
'  width: 100%;',
'  border-top-left-radius: 10px;',
'  border-top-right-radius: 10px;',
'}',
'',
'.card .content {',
'  display: flex;',
'  flex-direction: column;',
'  padding: 15px 10px;',
'}',
'',
'.card .header {',
'  display: flex;',
'  align-items: center;',
'}',
'',
'.card .profile-pic {',
'  background-image: url(''https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'');',
'  background-position: 50%;',
'  background-size: cover;',
'  height: 50px;',
'  width: 50px;',
'  border-radius: 50%;',
'}',
'',
'.card .detail {',
'  margin-left: 10px;',
'}',
'',
'.card .posted {',
'  font-size: 10px;',
'  padding-top: 3px;',
'}',
'',
'.card .desc {',
'  padding-top: 10px;',
'  line-height: 1.5;',
'}',
'',
'.card .tags {',
'  font-size: 12px;',
'  color: #FFDF3B;',
'  padding-top: 10px;',
'}',
'',
'.card .footer {',
'  display: flex;',
'  justify-content: space-between;',
'  padding-top: 20px;',
'}',
'',
'.card .footer .like {',
'  flex: 0 0 25%;',
'}',
'',
'.card .footer .comment {',
'  flex: 1;',
'}',
'',
'.card .footer .share {',
'  flex: 0 0 18%;',
'}',
'',
'.card .footer i {',
'  padding-right: 3px;',
'}',
'',
'.nav {',
'  background: #242C39;',
'  height: 80px;',
'  width: 100%;',
'  display: flex;',
'  justify-content: space-around;',
'  align-items: center;',
'  position: fixed;',
'  bottom: 0;',
'  box-shadow: 0 -4px 25px 0 rgba(0, 0, 0, .12);',
'}',
'',
'.nav .icon {',
'  flex: 1;',
'  text-align: center;',
'  color: #8E919A;',
'}',
'',
'.nav .icon i {',
'  padding-bottom: 10px;',
'  font-size: 20px;',
'}',
'',
'.nav .icon p {',
'  font-size: 12px;',
'}',
'',
'.active {',
'  color: #FFDF3B !important;',
'}',
'',
'::-webkit-scrollbar {',
'  display: none;',
'}',
'',
'.space {',
'  height: 200px;',
'}',
'anime({',
'  targets: ''.nav .icon i'',',
'  translateX: [100, 0],',
'  duration: 1200,',
'  opacity: [0, 1],',
'  delay: (el, i) => {',
'    return 300 + 100 * i;',
'  },',
'})',
'',
'anime({',
'  targets: ''.nav .icon p'',',
'  duration: 1200,',
'  opacity: [0, 1],',
'  delay: 700',
'})',
'',
'anime({',
'  targets: ''.live .person'',',
'  translateY: [100, 0],',
'  duration: 1200,',
'  delay: (el, i) => {',
'    return 1000 + 100 * i;',
'  },',
'})',
'',
'anime({',
'  targets: ''.like i'',',
'  easing: ''easeOutExpo'',',
'  scale: [2, 1],',
'  opacity: [0, 1],',
'  delay: 1200',
'})',
'',
'anime({',
'  targets: ''.comment i'',',
'  easing: ''easeOutExpo'',',
'  scale: [2, 1],',
'  opacity: [0, 1],',
'  delay: 1300',
'})',
'',
'anime({',
'  targets: ''.share i'',',
'  easing: ''easeOutExpo'',',
'  scale: [2, 1],',
'  opacity: [0, 1],',
'  delay: 1400',
'})',
'',
'anime({',
'  targets: ''.newsfeed .card'',',
'  translateY: [300, 0],',
'  easing: ''easeOutExpo'',',
'  opacity: [0, 1],',
'  delay: (el, i) => 700 + 300 * i',
'})',
'',
'</style>',
'',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <meta http-equiv="X-UA-Compatible" content="ie=edge">',
'  <link rel="stylesheet" href="style.css">',
'  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700&display=swap" rel="stylesheet">',
'  <script src="https://kit.fontawesome.com/9f37ddf547.js"></script>',
'  <title>Social Networking App</title>',
'</head>',
'',
'<body>',
'',
'  <section class="live">',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Miranda</p>',
'    </div>',
'    <div class="person live-active">',
'      <div class="profile-pic"></div>',
'      <p class="name">Taylor</p>',
'      <span><i class="fas fa-video"></i> Live</span>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Jack</p>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Jimmy</p>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Alex</p>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Halsey</p>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Jamie</p>',
'    </div>',
'    <div class="person">',
'      <div class="profile-pic"></div>',
'      <p class="name">Oliver</p>',
'    </div>',
'  </section>',
'',
'  <section class="newsfeed">',
'',
'    <div class="card">',
'      <div class="picture"></div>',
'      <div class="content">',
'        <div class="header">',
'          <div class="profile-pic"></div>',
'          <div class="detail">',
'            <p class="name">Miranda</p>',
'            <p class="posted">2 hours ago</p>',
'          </div>',
'        </div>',
'        <div class="desc">',
'          "Actually, the best gift you could have given her was a lifetime or adventures" Alice in Wonderland- I''ve',
'          always loved this quote. what''s your favourite quote?',
'        </div>',
'        <div class="tags">',
'          <span>#party</span>',
'          <span>#colorful</span>',
'        </div>',
'        <div class="footer">',
'          <div class="like">',
'            <i class="fas fa-heart"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="comment">',
'            <i class="fas fa-comment"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="share">',
'            <i class="fas fa-share"></i>',
'            <span>12k</span>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div class="card">',
'      <div class="picture"></div>',
'      <div class="content">',
'        <div class="header">',
'          <div class="profile-pic"></div>',
'          <div class="detail">',
'            <p class="name">Miranda</p>',
'            <p class="posted">2 hours ago</p>',
'          </div>',
'        </div>',
'        <div class="desc">',
'          "Actually, the best gift you could have given her was a lifetime or adventures" Alice in Wonderland- I''ve',
'          always loved this quote. what''s your favourite quote?',
'        </div>',
'        <div class="tags">',
'          <span>#party</span>',
'          <span>#colorful</span>',
'        </div>',
'        <div class="footer">',
'          <div class="like">',
'            <i class="fas fa-heart"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="comment">',
'            <i class="fas fa-comment"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="share">',
'            <i class="fas fa-share"></i>',
'            <span>12k</span>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div class="card">',
'      <div class="picture"></div>',
'      <div class="content">',
'        <div class="header">',
'          <div class="profile-pic"></div>',
'          <div class="detail">',
'            <p class="name">Miranda</p>',
'            <p class="posted">2 hours ago</p>',
'          </div>',
'        </div>',
'        <div class="desc">',
'          "Actually, the best gift you could have given her was a lifetime or adventures" Alice in Wonderland- I''ve',
'          always loved this quote. what''s your favourite quote?',
'        </div>',
'        <div class="tags">',
'          <span>#party</span>',
'          <span>#colorful</span>',
'        </div>',
'        <div class="footer">',
'          <div class="like">',
'            <i class="fas fa-heart"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="comment">',
'            <i class="fas fa-comment"></i>',
'            <span>12k</span>',
'          </div>',
'          <div class="share">',
'            <i class="fas fa-share"></i>',
'            <span>12k</span>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'',
'  </section>',
'',
'  <section class="nav">',
'    <div class="icon active">',
'      <i class="fas fa-fire"></i>',
'      <p>Home</p>',
'    </div>',
'    <div class="icon">',
'      <i class="fas fa-globe"></i>',
'      <p>Live</p>',
'    </div>',
'    <div class="icon">',
'      <i class="fas fa-comment-dots"></i>',
'      <p>Chats</p>',
'    </div>',
'    <div class="icon">',
'      <i class="fas fa-bell"></i>',
'      <p>Notifications</p>',
'    </div>',
'    <div class="icon">',
'      <i class="fas fa-user"></i>',
'      <p>Profile</p>',
'    </div>',
'  </section>',
'',
'  <div class="space"></div>',
'',
'  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.js"></script>',
'  <script src="main.js"></script>',
'</body>',
'',
'</html>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp.component_end;
end;
/
