prompt --application/pages/page_00002
begin
--   Manifest
--     PAGE: 00002
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>13501875225360637847
,p_default_application_id=>78259
,p_default_id_offset=>0
,p_default_owner=>'FLMPJGAZDYSOYO'
);
wwv_flow_imp_page.create_page(
 p_id=>2
,p_user_interface_id=>wwv_flow_imp.id(33247297241416359140)
,p_name=>'Use background picture change and slide show'
,p_alias=>'USE-BACKGROUND-PICTURE-CHANGE-AND-SLIDE-SHOW'
,p_step_title=>'Use background picture change and slide show'
,p_welcome_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<ul class="slideshow">',
'  <li><span></span></li>',
'  <li><span></span></li>',
'  <li><span></span></li>',
'  <li><span></span></li>',
'</ul>'))
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.t-Login-logo.fa {',
'	color: rgb(30, 30, 30);',
'}',
'',
'.t-Login-header {',
'	padding: 0px 0;',
'}',
'',
'.t-Login-region,',
'.t-MediaList {',
'	background: rgba(255, 255, 255, 0.65) !important;',
'}',
'',
'.slideshow {',
'	list-style: none;',
'	margin: 0px;',
'}',
'',
'.slideshow li span {',
'	width: 100%;',
'	height: 100%;',
'	position: absolute;',
'	top: 0px;',
'	left: 0px;',
'	color: transparent;',
'	background-size: cover;',
'	background-position: 50% 50%;',
'	background-repeat: none;',
'	opacity: 0;',
'	z-index: 0;',
'	-webkit-backface-visibility: hidden;',
'	backface-visibility: hidden;',
'	-webkit-animation: imageAnimation 48s linear infinite 0s;',
'	-moz-animation: imageAnimation 48s linear infinite 0s;',
'	animation: imageAnimation 48s linear infinite 0s;',
'}',
'',
'.slideshow li:nth-child(1) span {',
'	background-image: url(#APP_IMAGES#01.jpg);',
'}',
'',
'.slideshow li:nth-child(2) span {',
'	background-image: url(#APP_IMAGES#02.jpg);',
'	-webkit-animation-delay: 8s;',
'	-moz-animation-delay: 8s;',
'	animation-delay: 8s;',
'}',
'',
'.slideshow li:nth-child(3) span {',
'	background-image: url(#APP_IMAGES#03.jpg);',
'	-webkit-animation-delay: 16s;',
'	-moz-animation-delay: 16s;',
'	animation-delay: 16s;',
'}',
'',
'.slideshow li:nth-child(4) span {',
'	background-image: url(#APP_IMAGES#04.jpg);',
'	-webkit-animation-delay: 24s;',
'	-moz-animation-delay: 24s;',
'	animation-delay: 24s;',
'}',
'',
'.slideshow li:nth-child(5) span {',
'	background-image: url(#APP_IMAGES#05.jpg);',
'	-webkit-animation-delay: 32s;',
'	-moz-animation-delay: 32s;',
'	animation-delay: 32s;',
'}',
'',
'.slideshow li:nth-child(6) span {',
'	background-image: url(#APP_IMAGES#06.jpg);',
'	-webkit-animation-delay: 40s;',
'	-moz-animation-delay: 40s;',
'	animation-delay: 40s;',
'}',
'',
'@-webkit-keyframes imageAnimation {',
'	0% {',
'		opacity: 0;',
'		-webkit-animation-timing-function: ease-in;',
'	}',
'	12.5% {',
'		opacity: 1;',
'		-webkit-animation-timing-function: ease-out;',
'	}',
'	25% {',
'		opacity: 1;',
'	}',
'	37.5% {',
'		opacity: 0;',
'	}',
'	100% {',
'		opacity: 0;',
'	}',
'}',
'',
'@-moz-keyframes imageAnimation {',
'	0% {',
'		opacity: 0;',
'		-moz-animation-timing-function: ease-in;',
'	}',
'	12.5% {',
'		opacity: 1;',
'		-moz-animation-timing-function: ease-out;',
'	}',
'	25% {',
'		opacity: 1;',
'	}',
'	37.5% {',
'		opacity: 0;',
'	}',
'	100% {',
'		opacity: 0;',
'	}',
'}',
'',
'@keyframes imageAnimation {',
'	0% {',
'		opacity: 0;',
'		-webkit-animation-timing-function: ease-in;',
'		-moz-animation-timing-function: ease-in;',
'		animation-timing-function: ease-in;',
'	}',
'	12.5% {',
'		opacity: 1;',
'		-webkit-animation-timing-function: ease-out;',
'		-moz-animation-timing-function: ease-out;',
'		animation-timing-function: ease-out;',
'	}',
'	25% {',
'		opacity: 1;',
'	}',
'	37.5% {',
'		opacity: 0;',
'	}',
'	100% {',
'		opacity: 0;',
'	}',
'}',
'',
'.no-cssanimations .slideshow li span {',
'	opacity: 1;',
'}',
'',
'.t-Login-logo {',
'	background-image: url("#APP_IMAGES#app-82667-logo.png");',
'	background-size: cover;',
'	border-radius: 50%;',
'	width: 100px;',
'	height: 100px;',
'	background-image: url("#APP_IMAGES#app-82667-logo.png");',
'        cursor: pointer;',
'}',
''))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'11'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20200807110154'
);
wwv_flow_imp.component_end;
end;
/
