prompt --application/pages/page_00036
begin
--   Manifest
--     PAGE: 00036
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>13501875225360637847
,p_default_application_id=>78259
,p_default_id_offset=>0
,p_default_owner=>'FLMPJGAZDYSOYO'
);
wwv_flow_imp_page.create_page(
 p_id=>36
,p_user_interface_id=>wwv_flow_imp.id(33247297241416359140)
,p_name=>'Cards Profile'
,p_alias=>'CARDS-PROFILE'
,p_step_title=>'Cards Profile'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'$(''.fa-share-square'').bind("click", function() {',
'    $(this).next().toggleClass(''hover'');',
'  });',
'        ',
'',
'     $(".rotate").click(function(){',
' $(this).toggleClass("down")  ; ',
'});'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.flip-container.hover .flipper {',
'		-webkit-transform: rotateY(180deg) !important;',
'		-moz-transform: rotateY(180deg) !important;',
'    -o-transform: rotateY(180deg) !important;',
'		transform: rotateY(180deg) !important;',
'	}',
'',
'.flip-container, .front, .back {',
'	width: 210px ;',
'	height: 200px ;',
'}',
'',
'.flipper {',
'	-webkit-transition: 0.5s !important;',
'	-webkit-transform-style: preserve-3d !important;',
'',
'	-moz-transition: 0.5s !important;',
'	-moz-transform-style: preserve-3d !important;',
'  ',
'  -o-transition: 0.5s !important;',
'	-o-transform-style: preserve-3d !important;',
'',
'	transition: 0.5s !important;',
'	transform-style: preserve-3d !important;',
'',
'	position: relative !important;',
'}',
'',
'.front, .back {',
'	-webkit-backface-visibility: hidden !important;',
'	-moz-backface-visibility: hidden !important;',
'  -o-backface-visibility: hidden !important;',
'	backface-visibility: hidden !important;',
'',
'	position: absolute !important;',
'	top: 0 !important;',
'	left: 0 !important;',
'}',
'',
'.front {',
'	',
'	z-index: 2 !important;',
'}',
'',
'.back {',
'	-webkit-transform: rotateY(180deg) !important;',
'	-moz-transform: rotateY(180deg) !important;',
'  -o-transform: rotateY(180deg) !important;',
'	transform: rotateY(180deg) !important;',
'  ',
'}',
'',
'',
'.animate',
'{',
'	transition: all 0.1s !important;',
'	-webkit-transition: all 0.1s !important;',
'}',
'',
'.action-button',
'{',
'	/*position: relative;*/',
'	padding: 10px 40px !important;',
'  margin: 0px 10px 10px 0px !important;',
'  /*float: left;*/',
'	border-radius: 10px !important;',
'	font-family: ''Pacifico'', cursive !important;',
'	font-size: 20px !important;',
'	color: #FFF !important;',
'	text-decoration: none !important;',
'}',
'',
'.action-button:active',
'{',
'	transform: translate(0px,5px) !important;',
'  -webkit-transform: translate(0px,5px) !important;',
'	border-bottom: 1px solid !important;',
'} ',
'  ',
'',
'',
'#info_button {',
'    position:sticky;',
'    transition: .5s ease;',
'    top: 0%;',
'    left: 100%;',
'    padding-right: 0px;',
'}',
'',
'',
'',
'.card.small {',
'    height: 230px !important;',
'    width: 220px !important;',
'}',
'',
'.card.medium {',
'    height: 90px !important;',
'    width: 250px !important;',
'}',
'',
'.card .card-image img {',
'    display: block;',
'    border-radius: 2px 2px 0 0;',
'    position: relative;',
'    left: 5% !important;;',
'    right: 0;',
'    top: 0;',
'    bottom: 0;',
'    width: 100%;',
'}',
'',
'.card.small .card-action, .card.medium .card-action, .card.large .card-action {',
'    position: absolute !important;',
'    bottom: initial !important;',
'    left: 5px !important;',
'    right: 0 !important;',
'    top: 180px !important;',
'}',
'',
'.t-Card-wrap {',
'     border: 0px solid rgba(0,0,0,.075) !important; ',
'    background-clip: padding-box !important;',
'    width: 100% !important;',
'}',
'',
'.t-Card, .t-Card-icon, .t-Card-wrap, .t-Cards-item {',
'    position: relative;',
'    display: inline;',
'}',
'',
'.rotate{',
'    -moz-transition: all 2s linear;',
'    -webkit-transition: all 2s linear;',
'    transition: all 2s linear;',
'}',
'',
'.rotate.down{',
'    -moz-transform:rotate(180deg);',
'    -webkit-transform:rotate(180deg);',
'    transform:rotate(180deg);',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'10'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20210619134913'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(13212244745642109543)
,p_plug_name=>'Cards Profile'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(33247212693934359074)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'htp.p(''<!DOCTYPE html>'');',
'htp.p(''<html>'');',
'htp.p(''<head>'');',
'htp.p(''<meta name="viewport" content="width=device-width, initial-scale=1">'');',
'htp.p(''<style>',
'',
'</style>'');',
'',
'for u in (select a.PRODUCT_ID, ',
'        decode(nvl(dbms_lob.getlength(a.PRODUCT_IMAGE),0),0,null, ',
'       ''<img src="'' ',
'       ||apex_util.get_blob_file_src(''P9_PRODUCT_IMAGE'',a.PRODUCT_ID)||''"height="200" width="300"/>'') AS CARD_IMAGE,',
'       a.PRODUCT_DESCRIPTION,',
'     a.PRODUCT_NAME,',
'     a.PRODUCT_CODE,',
'     (select p.ORIGINAL_PRICE from PRODUCT_PRICE p where a.PRODUCT_ID = p.PRODUCT_ID) ORIGINAL_PRICE,',
'     (select p.SELLING_PRICE from PRODUCT_PRICE p where a.PRODUCT_ID = p.PRODUCT_ID) SELLPRICE,',
'     (select p.DISCOUNT from PRODUCT_PRICE p where a.PRODUCT_ID = p.PRODUCT_ID) DISPRICE',
'      from PRODUCT a)',
'',
'loop',
'htp.p(''<body>',
'<li class="t-Cards-item #CARD_MODIFIERS#" style="width:230px;">',
'<div class="col s12 m7" style="width:230px;">',
'        <div class="t-Card" style="width:220px;">',
'',
'      <div class="card small"  class="t-Card-wrap">',
'',
'    <div class="t-Card-wrap">',
'',
'       <i class="fa fa-share-square rotate" fa-5x id="info_button" title="Click To view Detail" style="color:#1E90FF;cursor:pointer"></i>',
'',
'       <div class="flip-container" style="border-top-width: 0px;">',
'  <div class="flipper"> ',
'',
'    <div class="front">',
'     <a href="#LINK#"  class="t-Card-wrap">',
'            <div class="t-Card-body"  class="t-Card-wrap">',
'        <div class="card-image"  class="t-Card-wrap">',
'        <img title=''||u.PRODUCT_NAME||'' src=''||u.CARD_IMAGE||''>',
'',
'                 <span  class="tooltip" title=''||u.PRODUCT_NAME||'' style="font-size:100%;color:black;margin-left:14px" ><b>''||u.CARD_IMAGE||''</b></span>',
'',
'                <div>',
'',
'            </div>        ',
'',
'        </div></div>       ',
'          </a>     ',
'<!-- Card Action Section is used to create buttons/link at the bottom of the cards  -->',
'      <div class="card-action">                            ',
'',
'                             <span class="tooltip" title="Content Comments" style="cursor:pointer"><i onclick="#LINK1#" class="material-icons" style="color:#2E8B57">''||u.PRODUCT_DESCRIPTION||''</i><a></a></span>',
'',
'                            <span class="tooltip" title="Known Bug" style="cursor:pointer;float: right"><i onclick="#LINK2#" class="material-icons" style="color:#FF0000;float: right">''||u.PRODUCT_CODE||''</i><a></a></span>',
'',
'        </div>',
'    </div>',
'',
'     <div class="back">',
'',
'            <div class="t-Card-body"  class="t-Card-wrap" >',
'',
'             <div style="text-align:left">',
'                 <span  style="font-size:90%;color:black;margin-left:6px"  ><b>''||u.PRODUCT_NAME||''</b></span></div>                                    ',
'                <div id="showm" >',
'',
'                    <span  class="more" style="font-size:80%;color:black">''||u.ORIGINAL_PRICE||''</span></div>',
'',
'                     </div>',
'',
'      <div class="card-action">',
'',
'          <span class="tooltip" title="Content Comments" style="cursor:pointer"><i onclick="#LINK1#" class="material-icons" style="color:#2E8B57">''||u.PRODUCT_DESCRIPTION||''</i><a></a></span>',
'',
'                           <span class="tooltip" title="Known Bug" style="cursor:pointer;float: right"><i onclick="javascript:var x=window.open("#","_blank");" class="material-icons" style="color:#FF0000;float: right">''||u.PRODUCT_CODE||''</i><a></a><'
||'/span>',
'',
'        </div>',
'    </div>',
'',
'  </div>',
'',
'</div>',
'',
'  </div>',
'',
'         </div>',
'',
'    </div>',
'    </div>',
'</li>'');',
'',
'    end loop;',
'    ',
'htp.p(''</body>'');',
'htp.p(''</html>'');'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_imp.component_end;
end;
/
