prompt --application/pages/page_00067
begin
--   Manifest
--     PAGE: 00067
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_page.create_page(
 p_id=>67
,p_user_interface_id=>wwv_flow_imp.id(14551754411696634465)
,p_name=>'Copy To Clipboard'
,p_alias=>'COPY-TO-CLIPBOARD'
,p_step_title=>'Copy To Clipboard'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  .K2_CBox {',
'      position: relative;',
'      background: #fff;',
'      width: 100%;',
'      border-radius: 6px;',
'      box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;',
'      padding: 8px 8px 1px;',
'  }',
'',
'  .K2_CBox .CB_Heading {',
'      display: flex;',
'      justify-content: space-between;',
'      align-items: center;',
'      margin-bottom: 15px',
'  }',
'',
'  .K2_CBox .CB_Heading span {',
'      margin: 0;',
'      font-weight: 700;',
'      font-family: inherit;',
'      font-size: 1.1rem',
'  }',
'',
'  .K2_CBox .C_box_main {',
'      cursor: pointer;',
'      display: inline-flex;',
'      align-items: center;',
'      padding: 12px;',
'      outline: 0;',
'      border: 0;',
'      border-radius: 50%;',
'      background: #004cbd;',
'      transition: all .3s ease;',
'      -webkit-transition: all .3s ease',
'  }',
'',
'  .K2_CBox .C_box_main:hover {',
'      opacity: .8',
'  }',
'',
'  .K2_CBox .C_box_main .CBox_icn {',
'      flex-shrink: 0;',
'      display: inline-block;',
'      width: 18px;',
'      height: 18px;',
'      background-image: url("data:image/svg+xml,<svg xmlns=''http://www.w3.org/2000/svg'' fill=''none'' stroke=''%23fefefe'' stroke-linecap=''round'' stroke-linejoin=''round'' stroke-width=''1.5'' viewBox=''0 0 24 24''><rect x=''5.54615'' y=''5.54615'' width=''16.45385'
||''' height=''16.45385'' rx=''4''/><path d=''M171.33311,181.3216v-8.45385a4,4,0,0,1,4-4H183.787'' transform=''translate(-169.33311 -166.86775)''/></svg>");',
'      background-size: cover;',
'      background-repeat: no-repeat;',
'      background-position: center',
'  }',
'',
'  .K2_CBox .C_box_main.copied {',
'      background: #2dcda7',
'  }',
'',
'  .K2_CBox .C_box_main.copied .CBox_icn {',
'      background-image: url("data:image/svg+xml,<svg xmlns=''http://www.w3.org/2000/svg'' fill=''none'' stroke=''%23fefefe'' stroke-linecap=''round'' stroke-linejoin=''round'' stroke-width=''1.5'' viewBox=''0 0 24 24''><path d=''M22 11.07V12a10 10 0 1 1-5.93-9.14''/'
||'><polyline points=''23 3 12 14 9 11''/></svg>")',
'  }',
'',
'  .tNtf span {',
'      position: fixed;',
'      left: 24px;',
'      bottom: -70px;',
'      display: inline-flex;',
'      align-items: center;',
'      text-align: center;',
'      justify-content: center;',
'      margin-bottom: 20px;',
'      z-index: 99981;',
'      background: #323232;',
'      color: rgba(255, 255, 255, .8);',
'      font-size: 14px;',
'      font-family: inherit;',
'      border-radius: 3px;',
'      padding: 13px 24px;',
'      box-shadow: 0 5px 35px rgba(149, 157, 165, .3);',
'      opacity: 0;',
'      transition: all .1s ease;',
'      animation: slideinwards 2s ease forwards;',
'      -webkit-animation: slideinwards 2s ease forwards',
'  }',
'',
'  @media screen and (max-width:500px) {',
'      .tNtf span {',
'          margin-bottom: 20px;',
'          left: 20px;',
'          right: 20px;',
'          font-size: 13px',
'      }',
'  }',
'',
'  @keyframes slideinwards {',
'      0% {',
'          opacity: 0',
'      }',
'',
'      20% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      50% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      80% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      100% {',
'          opacity: 0;',
'          bottom: -70px;',
'          visibility: hidden',
'      }',
'  }',
'',
'  @-webkit-keyframes slideinwards {',
'      0% {',
'          opacity: 0',
'      }',
'',
'      20% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      50% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      80% {',
'          opacity: 1;',
'          bottom: 0',
'      }',
'',
'      100% {',
'          opacity: 0;',
'          bottom: -70px;',
'          visibility: hidden',
'      }',
'  }',
'',
'  .darkMode .tNtf span {',
'      box-shadow: 0 10px 40px rgba(0, 0, 0, .2)',
'  }',
'',
'  .pre_code_css {',
'      position: relative;',
'      background: #13052e;',
'      display: block;',
'      direction: ltr;',
'      unicode-bidi: bidi-override;',
'      color: #fff;',
'      word-break: normal;',
'      border: none;',
'      border-left: 7px solid #F9BC00;',
'      width: 100%;',
'      //margin: 1em auto;',
'      background-color: #13052e;',
'      border-radius: 8px;',
'  }',
'',
'  .code_css {',
'      font-size: 14px;',
'      font-family: source code pro, Inconsolata, lucida console, Terminal, courier new, Courier;',
'      line-height: 1.3;',
'      white-space: pre-wrap;',
'      padding: 1em;',
'      width: 100%;',
'  }'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'htp.p(''<style>',
'.colors-to-choose {',
'  display: flex;',
'  justify-content: center;',
'  flex-wrap: nowrap;',
'    ',
'    &>div {',
'      padding: 10px;',
'      margin: 20px 5px 0;',
'  }',
'}',
'</style>',
''');',
'htp.p(''',
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <meta http-equiv="X-UA-Compatible" content="ie=edge">',
'  <title>Copy content on click</title>',
'</head>',
'<body>',
'  <div class="colors-to-choose">',
'    <div class="color" style="background: rgb(55, 175, 233);">#37AFE9</div>',
'    <div class="color" style="background: rgb(52, 75, 100);">#344B64</div>',
'    <div class="color" style="background: rgb(153, 222, 255);">#99DEFF</div>',
'    <div class="color" style="background: rgb(250, 251, 251);">#FAFBFB</div>',
'    <div class="color" style="background: rgb(233, 235, 243);">#E9EBF3</div>',
'    <div class="color" style="background: rgb(255, 255, 255);">#FFFFFF</div>',
'    <div class="color" style="background: rgb(0, 110, 169);">#006EA9</div>',
'  </div>  ',
'</body>',
'</html>   ',
''');',
'htp.p(''',
'<script>',
'',
'var color = document.querySelectorAll(".color") //DOM selector',
'',
'//Loop through all elements and attaching event listener',
'color.forEach(el => {',
'  el.addEventListener("click",copyText)',
'})',
'',
'// function for selecting the text of an element based on the event.target (supporting IE)',
'function selectText() {',
'    var element = event.target',
'    var range;',
'    if (document.selection) {',
'        // IE',
'        range = document.body.createTextRange();',
'        range.moveToElementText(element);',
'        range.select();',
'    } else if (window.getSelection) {',
'        range = document.createRange();',
'        range.selectNode(element);',
'        window.getSelection().removeAllRanges();',
'        window.getSelection().addRange(range);',
'    }',
'}',
'',
'// function for copying selected text in clipboard',
'function copyText() {',
'    selectText();',
'    alert("Color code " + event.target.innerText + " copied in clipboard")',
'    document.execCommand("copy");',
'}',
'',
'',
'  </script>',
''');'))
,p_page_component_map=>'10'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220729111133'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(53679345145071983815)
,p_plug_name=>'Copy To Clipboard'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8" />',
'<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
'<title>Document</title>',
'<style>',
'   body {',
'      font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;',
'   }',
'   .result {',
'      font-size: 18px;',
'      font-weight: 500;',
'      color: rebeccapurple;',
'   }',
'   input,',
'   button {',
'      padding: 8px;',
'   }',
'</style>',
'</head>',
'<body>',
'<div class="K2_CBox">',
'		<div class="CB_Heading">',
'			<span>Paste The Following Code</span> ',
'            <button class="C_box_main" id="copy1" type="button">',
'                <i class="CBox_icn"></i>',
'            </button>',
'		</div>',
'		<div class="textCopy" type="text">',
'			<pre class="pre_code_css"> ',
'            <code class="code_css"> ',
'    111111111111111',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});',
'',
'     </code></pre>',
'		</div>',
'	</div>',
'	<div class="tNtf" id="toastNotif"></div>',
'',
'',
'',
'<input type="text" placeholder="paste here" />',
'',
'<script>',
'   let resEle = document.querySelector(".result");',
' let BtnEle = document.querySelector(".C_box_main");',
'   let textCopyEle = document.querySelector(".textCopy");',
'   BtnEle.addEventListener("click", () => {',
'      textCopyEle.select();',
'      document.execCommand("copy");',
'      removeAllRanges();',
'    classList.add("copied");',
'    document.getElementById("toastNotif").innerHTML="<span>Copied to Clipboard!</span>";',
'    setTimeout(()=>{o.classList.remove("copied")},3e3);',
'',
'   });',
'</script>',
'</body>',
'</html>',
'',
'',
'',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(53679345344412983817)
,p_plug_name=>'Copy To Clipboard 22'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'htp.p(''',
'<style>',
'.copy {',
'  cursor: copy;   ',
'}',
'</style>',
''');',
'htp.p(''',
'<p><span class="copy">',
'<button class="C_box_main" id="btn" type="button"><i class="CBox_icn"></i></button>',
'       <pre class="prettyprint lang-scm highlight" style="position:relative;background:#13052e;display:block;direction:ltr;unicode-bidi:bidi-override;color:#fff;word-break:normal;border:none;border-left:7px solid #F9BC00;width:100%;margin:1em auto;ba'
||'ckground-color:#13052e;border-radius:8px">',
'             <code style="font-size:14px;font-family:source code pro,Inconsolata,lucida console,Terminal,courier new,Courier;line-height:1.3;white-space:pre-wrap;padding:1em">',
'',
' 111111111111111',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code>',
'    </pre>',
'</span></p> </br> </br> ',
'<p><span class="copy">',
'<button class="C_box_main" id="btn" type="button"><i class="CBox_icn"></i></button>',
'       <pre class="prettyprint lang-scm highlight" style="position:relative;background:#13052e;display:block;direction:ltr;unicode-bidi:bidi-override;color:#fff;word-break:normal;border:none;border-left:7px solid #F9BC00;width:100%;margin:1em auto;ba'
||'ckground-color:#13052e;border-radius:8px">',
'             <code style="font-size:14px;font-family:source code pro,Inconsolata,lucida console,Terminal,courier new,Courier;line-height:1.3;white-space:pre-wrap;padding:1em">',
'',
' 222222222',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code>',
'    </pre>',
'</span></p></br> </br> ',
'<p><span class="copy">',
'    <button class="C_box_main" id="btn" type="button"><i class="CBox_icn"></i></button>',
'       <pre class="prettyprint lang-scm highlight" style="position:relative;background:#13052e;display:block;direction:ltr;unicode-bidi:bidi-override;color:#fff;word-break:normal;border:none;border-left:7px solid #F9BC00;width:100%;margin:1em auto;ba'
||'ckground-color:#13052e;border-radius:8px">',
'             <code style="font-size:14px;font-family:source code pro,Inconsolata,lucida console,Terminal,courier new,Courier;line-height:1.3;white-space:pre-wrap;padding:1em">',
'',
' 333333333333',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code>',
'    </pre>',
'</span></p>',
'',
'<button type="button" id="btn">Copy</button>',
''');',
'htp.p(''',
'<script>',
'function copyToClipboard(text) {',
'    var selected = false;',
'    var el = document.createElement("textarea");',
'    el.value = text;',
'    el.setAttribute("readonly", "");',
'    el.style.position = "absolute";',
'    el.style.left = "-9999px";',
'    document.body.appendChild(el);',
'    if (document.getSelection().rangeCount > 0) {',
'        selected = document.getSelection().getRangeAt(0)',
'    }',
'    el.select();',
'    document.execCommand("copy");',
'    document.body.removeChild(el);',
'    if (selected) {',
'        document.getSelection().removeAllRanges();',
'        document.getSelection().addRange(selected);',
'        console.log(event.clipboardData.getData("text"))',
'    }',
'};',
'  </script>',
''');'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(53679345437370983818)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>40
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="highlight">',
'    <pre><code>    111111111111111',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code></pre></div>',
'<div class="highlight">',
'    <pre><code>    222222222222222',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code></pre></div>',
'<div class="highlight">',
'    <pre><code>    33333333333333333333',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code></pre></div>',
'<div class="highlight">',
'    <pre><code>    44444444444444444444',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code></pre></div>',
'<div class="highlight">',
'    <pre><code>    111111111111111',
'    body: "This is my notification",',
'    icon: "ICON_URL",',
'    image: "IMAGE_URL"',
'});</code></pre></div>',
'',
'<script>',
'const svgCopy = ''<svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true"><path fill-rule="evenodd" d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 010 1.5h-1.5a.25.25 0 00-.25.25v7.5c0 .138.112.25.25.2'
||'5h7.5a.25.25 0 00.25-.25v-1.5a.75.75 0 011.5 0v1.5A1.75 1.75 0 019.25 16h-7.5A1.75 1.75 0 010 14.25v-7.5z"></path><path fill-rule="evenodd" d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0114.25 11h-7.5A1.75 1.75 0 015 '
||'9.25v-7.5zm1.75-.25a.25.25 0 00-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 00.25-.25v-7.5a.25.25 0 00-.25-.25h-7.5z"></path></svg>'';',
'const svgCheck = ''<svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true"><path fill-rule="evenodd" fill="rgb(63, 185, 80)" d="M13.78 4.22a.75.75 0 010 1.06l-7.25 7.25a.75.75 0 01-1.06 0L2.22 9.28a.'
||'75.75 0 011.06-1.06L6 10.94l6.72-6.72a.75.75 0 011.06 0z"></path></svg>'';',
'const addCopyButtons = (clipboard)=>{',
'    document.querySelectorAll("pre > code").forEach((codeBlock)=>{',
'        // Create button DOM element',
'        const button = document.createElement("button");',
'        button.className = "copy-code-button";',
'        button.type = "button";',
'        button.innerHTML = svgCopy;',
'        button.addEventListener("click", ()=>{',
'            clipboard.writeText(codeBlock.innerText).then(()=>{',
'                button.blur();',
'                button.innerHTML = svgCheck;',
'                setTimeout(()=>(button.innerHTML = svgCopy), 2000);',
'            }',
'            , (error)=>(button.innerHTML = "Error"));',
'        }',
'        );',
'        // Attach button to DOM (.highlight > button > pre > code)',
'        const pre = codeBlock.parentNode;',
'        pre.parentNode.insertBefore(button, pre);',
'    }',
'    );',
'}',
';',
'',
'if (navigator && navigator.clipboard) {',
'    addCopyButtons(navigator.clipboard);',
'} else {',
'    const script = document.createElement("script");',
'    script.src = "https://cdnjs.cloudflare.com/ajax/libs/clipboard-polyfill/2.7.0/clipboard-polyfill.promise.js";',
'    script.integrity = "sha256-waClS2re9NUbXRsryKoof+F9qc1gjjIhc2eT7ZbIv94=";',
'    script.crossOrigin = "anonymous";',
'    script.onload = ()=>addCopyButtons(clipboard);',
'    document.body.appendChild(script);',
'}',
'</script>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp.component_end;
end;
/
