prompt --application/pages/page_00076
begin
--   Manifest
--     PAGE: 00076
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_page.create_page(
 p_id=>76
,p_user_interface_id=>wwv_flow_imp.id(14551754411696634465)
,p_name=>'Chat Application'
,p_alias=>'ADD-SEARCH-ITEM-SIDE-NAVIGATION-MENU-IN-ORACLE-APEX'
,p_step_title=>'Chat Application'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'@import url(''https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap'');',
'',
'*{',
'    margin: 0;',
'    padding: 0;',
'    box-sizing: border-box;',
'    font-family: ''Poppins'', sans-serif;',
'',
'}',
'main{',
'    width: 100%;',
'    height: 100vh;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'    background: #dd7d94;',
'}',
'.chat-container {',
'    width: 60rem;',
'    height: 95vh;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'   ',
'}',
'.chate-liste{',
'    width: 40%;',
'    height: 100%;',
'    background: #514685;',
'    display: flex;',
'    flex-direction: column;',
'    position: relative;',
'}',
'.chate{',
'    width: 60%;',
'    height: 100%;',
'    display: flex;',
'   ',
'    align-items: center;',
'    flex-direction: column;',
'    background: #f6f2f2;',
'',
'}',
'.m-info{',
'    margin-top: 20px;',
'    position: relative;',
'    width: 90%;',
'    height: 10vh;',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'}',
'',
'.m-info .avatar{',
'margin-left: 10px;',
'}',
'.p-info{',
'    position: absolute;',
'    right: 15%;',
'    color:#fff;',
'}',
'.p-info h3{',
'    font-weight: 100;',
'}',
'.p-info span{',
'    font-size: 15px;',
'    color: rgb(233,233,233);',
'}',
'.icon{',
'    position: relative;',
'    margin-right: 10px;',
'}',
'.icon i{',
'    position: absolute;',
'    bottom: 30px;',
'    right: -35%;',
'    color: rgb(233,233,233);',
'    cursor: pointer;',
'',
'}',
'.search-box{',
'    width: 90%;',
'    height: 1rem;',
'    display: flex;',
'    margin: 1rem;',
'    align-items: center;',
'',
'}',
'.search-box i{',
'margin-right: 20px;',
'color: white;',
'font-size: 14px;',
'}',
'.search-box input{',
'    font-size: 16px;',
'    width: 70%;',
'    background: none;',
'    outline: none;',
'    border: none;',
'    color: rgb(233,233,233);',
'',
'}',
'.search-box input::placeholder{',
'    color:  rgb(199, 199, 199);',
'}',
'.ms-a{',
'    display: flex;',
'    align-items: center;',
'    width: 100%;',
'    height: 4rem;',
'}',
'.ms-a .avatar{',
'    margin-left: 5px;',
'    margin-right: 10px;',
'}',
'.mesg-info{',
'    width: 90%;',
'    display: flex;',
'    justify-content: center;',
'    flex-direction: column;',
'',
'}',
'.ms-info{',
'    width: 100%;',
'    display: flex;',
'    justify-content: space-between;',
'}',
'.sender-name{',
'    color: white;',
'    letter-spacing: 1px;',
'',
'}',
'.time{',
'    color: #a5a5a5;',
'    font-size: 14px;',
'    margin-right: 20px;',
'}',
'.time span{',
'    color: black;',
'    border-radius: 100%;',
'    margin: 10px;',
'}',
'.action span{',
'    font-size: 12px;',
'    color:#a5a5a5;',
'}',
'.ms-active{',
'    padding: 0px 5px;',
'    background: #f8f403;',
'    border-radius: 100%;',
'    font-size: 10px;',
'}',
'.new-chate{',
'    width: 60px;',
'    height: 60px;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'    background: #34debb;',
'    position: absolute;',
'    border-radius: 100%;',
'    bottom: 8px;',
'    right: 12px;',
'    cursor: pointer;',
'    box-shadow: 2px 1px 29px -8px rgba(52,222,187,1);',
'    ',
'}',
'.new-chate span{',
'    font-size: 2rem;',
'    color: white;',
'}',
'.chat-active{',
'    background:#332869 ;',
'}',
'.last-chate{',
'    opacity: .5;',
'}',
'',
'',
'.chate-header{',
'    width: 100%;',
'    height: 10vh;',
'    background: #34debb;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'}',
'.header-content{',
'    width: 90%;',
'    height: 100%;',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'}',
'.sender-action{',
'    display: flex;',
'    flex-direction: column;',
'    align-items: center;',
'}',
'.sender-action h3{',
'    font-weight: 100;',
'    color: white;',
'    letter-spacing: 1px;',
'}',
'.sender-action span{',
'    font-size: 15px;',
'    color: #ececec;',
'}',
'.icons i{',
'    color: #ececec;',
'    font-size: 15px;',
'    margin-left: 15px;',
'    cursor: pointer;',
'}',
'.chate-body{',
'    width: 90%;',
'    display: flex;',
'    flex-direction: column;',
'}',
'.message-sender, .message-recever{',
'    width: 100%;',
'    display: flex;',
'    align-items: center;',
'    margin-top: 1rem;',
'}',
'.message-sender{',
'    flex-direction: row-reverse;',
'}',
'.message-sender-message{',
'    height: auto;',
'    width: 50%;',
'    margin-right: 1rem;',
'    background: #fff;',
'    border-radius: 30px;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'}',
'.message-sender-message p{',
'    padding: 10px;',
'    font-size: .8rem;',
'    text-align: center;',
'}',
'.message-sender-icon{',
'    margin-right: 15px;',
'    color: #34debb;',
'    font-size: 12px;',
'}',
'.message-sender-avatar {',
'    margin-right: 17px;',
'}',
'.messag-box{',
'    width: 100%;',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'    position: relative;',
'    ',
'}',
'.message-box-aria{',
'    width: 46%;',
'    background: #fff;',
'    position: absolute;',
'    top: 83%;',
'    border-radius: 30px;',
'    box-shadow: 0px 7px 23px -8px rgba(204,202,204,1);',
'}',
'.message-box-aria input{',
'    width: 90%;',
'    height: 4rem;',
'    border: none;',
'    outline: none;',
'    background: none;',
'    margin-left: 20px;',
'}',
'.message-box-aria input::placeholder{',
'    color: gray;',
'}',
'.message-box-aria i{',
'    color: gray;',
'    cursor: pointer;',
'}',
'',
''))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220729111133'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(23262956381442407314)
,p_plug_name=>'Chat Application'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'    <meta charset="UTF-8">',
'    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'    <script src=''https://kit.fontawesome.com/a076d05399.js''></script>',
'    <link rel="stylesheet" href="style.css">',
'    <title>Application chate</title>',
'</head>',
'<body>',
'   <main>',
'       <div class="chat-container">',
'           <div class="chate-liste">',
'<div class="m-info">',
'    <div class="avatar">',
'        <img src="images/iconfinder_anime_spirited_away_no_face_nobody_4043233.png"',
'        width="60px" alt="">',
'    </div>',
'    <div class="p-info">',
'        <div class="pname">',
'            <h2>Imade EL Mendoub</h2>',
'            <span class="p-disc"> Web Developer</span>',
'        </div>',
'        <div class="icon">',
'            <i class=''fas fa-bars''></i>',
'        </div>',
'    </div>',
'</div>',
'<div class="search-box">',
'    <i class=''fas fa-search''></i>',
'    <input type="text" placeholder="Search for chate or gorupe chate">',
'</div>',
'<div class="ms-a chat-active">',
'    <div class="avatar">',
'        <img src="images/iconfinder_afro_woman_female_person_4043231.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Trixie Mattel</span>',
'            <span class="time"> just now <span class="msge-num ms-active ">2</span></span>',
'        </div>',
'        <div class="action">',
'            <span>Typing...</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_batman_hero_avatar_comics_4043232.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Jhone Alex</span>',
'            <span class="time"> Yesterday<span class="msge-num"></span></span>',
'        </div>',
'        <div class="action">',
'            <span>Hi how are you?</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_girl_female_woman_avatar_4043251.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Hanan Soud</span>',
'            <span class="time"> 20:24 <span class="msge-num"></span></span>',
'        </div>',
'        <div class="action">',
'            <span>Wher are you ?</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_hipster_beard_male_man_4043255.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Mohamed Ayoub</span>',
'            <span class="time"> just now <span class="msge-num ms-active">4</span></span>',
'        </div>',
'        <div class="action">',
'            <span>Not done yet</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_man_male_avatar_portrait_4043260.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name">My Doctor</span>',
'            <span class="time"> just now <span class="msge-num  ms-active">5</span></span>',
'        </div>',
'        <div class="action">',
'            <span>Typing...</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_scientist_einstein_avatar_professor_4043274.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Mome</span>',
'            <span class="time"> 2 days ago <span class="msge-num"></span></span>',
'        </div>',
'        <div class="action">',
'            <span><i class=''fas fa-video'' style="color: rgb(207, 207, 207);"></i> You ertr in a video vall</span>',
'        </div>',
'    </div>',
'</div>',
'<div class="ms-a last-chate ">',
'    <div class="avatar">',
'        <img src="images/iconfinder_afro_woman_female_person_4043231.png" width="50px" alt="">',
'    </div>',
'    <div class="mesg-info ">',
'        <div class="ms-info">',
'            <span class=" sender-name"> Mouna Laria</span>',
'            <span class="time"> just now <span class="msge-num"></span></span>',
'        </div>',
'        <div class="action">',
'            <span>Typing...</span>',
'        </div>',
'    </div>',
'    ',
'</div>',
'<div class="new-chate">',
'    <span>+</span>',
'</div>',
'',
'',
'           </div>',
'           <div class="chate">',
'               <div class="chate-header">',
'                   <div class="header-content">',
'                   <div class="sender-avatar">',
'                       <img src="images/iconfinder_afro_woman_female_person_4043231.png" width="50px" alt="">',
'                   </div>',
'                   <div class="sender-action">',
'                       <h3>Trixie Mattel</h3>',
'                       <span>Typing...</span>',
'                   </div>',
'                   <div class="icons">',
'                    <i class=''fas fa-user-plus''></i>',
'                    <i class=''fas fa-search''></i>',
'                    <i class=''fas fa-ellipsis-v''></i>',
'                   </div>',
'                </div>',
'               </div>',
'               <div class="chate-body">',
'                <div class="message-sender">',
'                    <div class="message-sender-avatar">',
'                        <img src="images/iconfinder_anime_spirited_away_no_face_nobody_4043233.png" width="50px" alt="">',
'                    </div>',
'                    <div class="message-sender-message  ">',
'                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. </p>',
'                    </div>',
'                    <div class="message-sender-icon"><i class=></i></div>',
'                    ',
'                </div>',
'                <div class="message-recever">',
'                    <div class="message-sender-avatar">',
'                        <img src="images/iconfinder_afro_woman_female_person_4043231.png" width="50px" alt="">',
'                    </div>',
'                    <div class="message-sender-message rece">',
'                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. </p>',
'                    </div>',
'                    <div class="message-sender-icon"><i class=''fas fa-heart''></i></div>',
'',
'                </div>',
'                <div class="message-sender">',
'                    <div class="message-sender-avatar">',
'                        <img src="images/iconfinder_anime_spirited_away_no_face_nobody_4043233.png" width="50px" alt="">',
'                    </div>',
'                    <div class="message-sender-message ">',
'                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. </p>',
'                    </div>',
'                    <div class="message-sender-icon"><i class=></i></div>',
'                    ',
'                </div>',
'                <div class="message-recever">',
'                    <div class="message-sender-avatar">',
'                        <img src="images/iconfinder_afro_woman_female_person_4043231.png" width="50px" alt="">',
'                    </div>',
'                    <div class="message-sender-message rece">',
'                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. </p>',
'                    </div>',
'                    <div class="message-sender-icon"><i class=''fas fa-heart''></i></div>',
'',
'                </div>',
'                <div class="message-sender">',
'                    <div class="message-sender-avatar">',
'                        <img src=" images/iconfinder_anime_spirited_away_no_face_nobody_4043233.png" width="50px" alt="">',
'                    </div>',
'                    <div class="message-sender-message ">',
'                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. </p>',
'                    </div>',
'                    <div class="message-sender-icon"><i class=></i></div>',
'                    ',
'                </div>',
'                <div class="message-box">',
'                    <div class="message-box-aria">',
'                        <input type="text" placeholder="Type a message..">',
'                        <i class=''far fa-smile''></i>',
'                    </div>',
'                </div>',
'                   ',
'                ',
'        </div>',
'               </div>',
'           </div>',
'       </div>',
'   </main>',
'</body>',
'</html>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp.component_end;
end;
/
