prompt --application/pages/page_00031
begin
--   Manifest
--     PAGE: 00031
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_page.create_page(
 p_id=>31
,p_user_interface_id=>wwv_flow_imp.id(14551754411696634465)
,p_name=>'SliderBar in HTML and CSS'
,p_alias=>'SLIDERBAR-IN-HTML-AND-CSS'
,p_step_title=>'SliderBar in HTML and CSS'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'@import url(''https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap'');',
'*{',
'  margin: 0;',
'  padding: 0;',
'  box-sizing: border-box;',
'  font-family: "Poppins" , sans-serif;',
'}',
':root{',
'    --black-color:#11101d;',
'    --white-color:#fff;',
'    --sky-color:#E4E9F7;',
'    --light-black:#1d1b31;',
'}',
'body{',
'  position: relative;',
'  min-height: 100vh;',
'  width: 100%;',
'  overflow: hidden;',
'}',
'::selection{',
'  color:var(--white-color);',
'  background: var(--black-color);',
'} ',
'',
'/*',
'.sidebar{',
'  position:fixed;',
'  top:0;',
'  left:0;',
'  height:100%;',
'  width:78px;',
'  background:var(--black-color);',
'  padding:6px 14px;',
'  z-index:99;',
'  transition:all 0.5s ease;',
'}',
'*/',
'.sidebar {',
'    position: fixed;',
'    top: 33px;',
'    left: 32px;',
'    height: 100%;',
'    width: 95px;',
'    background: var(--black-color);',
'    /* padding: 0PX 0px; */',
'    z-index: 99;',
'    transition: all 0.5s ease;',
'}',
'',
'',
'.sidebar.active{',
'  width:240px;',
'}',
'.sidebar .logo_content .logo{',
'  color:var(--white-color);',
'  display: flex;',
'  height:60px;',
'  width:100%;',
'  align-items: center;',
'  opacity: 0;',
'  pointer-events: none;',
'  transition:all 0.5s ease;',
'}',
'.sidebar.active .logo_content .logo{',
'  opacity:1;',
'  pointer-events: none;',
'}',
'.logo_content .logo .logo_name{',
'  font-size: 20px;',
'  font-weight: 400;',
'}',
'.sidebar #btn{',
'  position:absolute;',
'  color:var(--white-color);',
'  top:6px;',
'  left:50%;',
'  font-size: 22px;',
'  height:50px;',
'  width:50px;',
'  text-align: center;',
'  line-height: 50px;',
'  transform: translateX(-50%);',
'  cursor: pointer;',
'}',
'.sidebar.active #btn{',
'  left:90%;',
'}',
'.sidebar ul{',
'  margin-top:20px;',
'}',
'.sidebar ul li{',
'  position:relative;',
'  height:50px;',
'  width:100%;',
'  margin:5px 0;',
'  list-style: none;',
'  line-height: 50px;',
'}',
'.sidebar ul li .tooltip{',
'  position:absolute;',
'  left:125px;',
'  top:0;',
'  transform:translate(-50%, -50%);',
'  border-radius: 6px;',
'  height:35px;',
'  width:120px;',
'  background: var(--white-color);',
'  line-height: 35px;',
'  text-align: center;',
'  box-shadow: 0 5px 10px rgba(0,0,0,0.2);',
'  transition:0s;',
'  opacity:0;',
'  pointer-events: none;',
'  display:block;',
'}',
'.sidebar ul li .tooltip::before{',
'  content:'''';',
'  width:0;',
'  height:0;',
'  border-top:10px solid transparent;',
'  border-bottom:10px solid transparent;',
'  border-right:10px solid var(--white-color);',
'  position:absolute;',
'  left:-8px;',
'  top:7px;',
'}',
'.sidebar.active ul li .tooltip{',
'  display:none;',
'}',
'.sidebar ul li:hover .tooltip{',
'  transition:all 0.5s ease;',
'  opacity:1;',
'  top:50%;',
'}',
'.sidebar ul li input{',
'  position:absolute;',
'  height:100%;',
'  width:100%;',
'  left:0;',
'  top:0;',
'  border-radius: 12px;',
'  outline:none;',
'  border:none;',
'  background: #1d1b31;',
'  padding-left:50px;',
'  font-size: 18px;',
'  color:var(--white-color);',
'}',
'.sidebar ul li .bx-search{',
'  position:relative;',
'  z-index: 99;',
'  color:var(--white-color);',
'  font-size: 22px;',
'  transition:all 0.5s ease;',
'}',
'.sidebar ul li .bx-search:hover{',
'  background:var(--white-color);',
'  color:#1d1b31;',
'}',
'.sidebar ul li a{',
'  color:var(--white-color);',
'  display:flex;',
'  align-items:center;',
'  text-decoration: none;',
'  border-radius: 12px;',
'  white-space: nowrap;',
'  transition:all 0.4s ease;',
'}',
'',
'.sidebar ul li a:hover{',
'  color:var(--black-color);',
'  background:var(--white-color);',
'}',
'.sidebar ul li i{',
'  font-size: 18px;',
'  font-weight: 400;',
'  height:50px;',
'  min-width: 50px;',
'  border-radius: 12px;',
'  line-height: 50px;',
'  text-align: center;',
'}',
'.sidebar .links_name{',
'  font-size: 15px;',
'  font-weight: 400;',
'  opacity:0;',
'  pointer-events: none;',
'  transition:all 0.3s ease;',
'}',
'.sidebar.active .links_name{',
'  transition:0s;',
'  opacity:1;',
'  pointer-events: auto;',
'}',
'.sidebar .content{',
'  position:absolute;',
'  color:var(--white-color);',
'  bottom:0;',
'  left:0;',
'  width:100%;',
'}',
'.sidebar .content .user{',
'  position:relative;',
'  padding:10px 18px;',
'  height:100px;',
'  background: none;',
'  transition:all 0.4s ease;',
'}',
'.sidebar.active .content .user{',
'  background:var(--light-black);',
'}',
'.content .user .user_details{',
'  display:flex;',
'  align-items:center;',
'  opacity:0;',
'  pointer-events: none;',
'  white-space: nowrap;',
'  transition:all 0.4s ease;',
'}',
'.sidebar.active .user .user_details{',
'  opacity:1;',
'  pointer-events: auto;',
'}',
'.content .user .user_details img{',
'  height:45px;',
'  width:45px;',
'  object-fit: cover;',
'  border-radius: 12px;',
'}',
'.name_job{',
'  margin-left:10px;',
'}',
' .user_details .name{',
'  font-size: 15px;',
'  font-weight: 400;',
'}',
' .user_details .job{',
'  font-size: 12px; ',
'}',
' #log_out{',
'  position:absolute;',
'  bottom:5px;',
'  left:50%;',
'  transform:translateX(-50%);',
'  min-width: 50px;',
'  line-height: 150px;',
'  font-size: 20px;',
'  border-radius: 12px;',
'  text-align: center;',
'  transition:all 0.4s ease;',
'}',
'.sidebar.active .user #log_out{',
'  left:80%;',
'  background:none;',
'}',
'.home_content{',
'  position:absolute;',
'  height:100%;',
'  width:calc(100% - 78px);',
'  left:78px;',
'  background:var(--sky-color);',
'  padding:20px;',
'  box-shadow: 0 5px 10px rgba(0,0,0,0.2);',
'  transition:all 0.5s ease;',
'}',
'.sidebar.active ~ .home_content{',
'  z-index:100;',
'  width:calc(100% - 240px);',
'  left:240px;',
'}',
'.home_content .text{',
'  font-size: 25px;',
'  font-weight: 600;',
'  color:var(--light-black);',
'  margin-bottom:15px;',
'}',
'.home_content p{',
'  margin-bottom:15px;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'11'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220729111133'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(27191669223705241706)
,p_plug_name=>'Slider Bar'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html> ',
'<html lang="en" dir="ltr">',
'  <head>',
'    <meta charset="UTF-8">',
'    <title> Responsive Sidebar Menu  | jABER IT LTD </title>',
'    <link rel="stylesheet" href="style.css">',
'    <!-- Boxicons CDN Link -->',
'    <link href=''https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css'' rel=''stylesheet''>',
'     <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'   </head>',
'<body>',
'   <div class="sidebar">',
'     <div class="logo_content">',
'       <div class="logo">',
'         <div class="logo_name">&nbsp;&nbsp;&nbsp;&nbsp; jABER IT LTD</div>',
'       </div>',
'       <i class=''bx bx-menu'' id="btn"></i>',
'     </div>',
'     <ul class="nav_list">',
'       <li>',
'          <i class=''bx bx-search''></i>',
'          <input type="text" placeholder="Search...">',
'          <span class="tooltip">Search</span>',
'       </li>',
'       <li>',
'        <a href="#">',
'         <i class=''bx bx-grid-alt''></i>',
'         <span class="links_name">Dashboard</span>',
'        </a>',
'        <span class="tooltip">Dashboard</span>',
'      </li>',
'       <li>',
'         <a href="#">',
'          <i class=''bx bx-user''></i>',
'          <span class="links_name">User</span>',
'         </a>',
'         <span class="tooltip">User</span>',
'       </li>',
'       <li>',
'        <a href="#">',
'         <i class=''bx bx-chat''></i>',
'         <span class="links_name">Messages</span>',
'        </a>',
'        <span class="tooltip">Messages</span>',
'      </li>',
'      <li>',
'        <a href="#">',
'         <i class=''bx bx-pie-chart-alt-2''></i>',
'         <span class="links_name">Analytics</span>',
'        </a>',
'        <span class="tooltip">Analytics</span>',
'      </li>',
'      <li>',
'        <a href="#">',
'         <i class=''bx bx-folder''></i>',
'         <span class="links_name">File Manager</span>',
'        </a>',
'        <span class="tooltip">File Manager</span>',
'      </li>',
'      <li>',
'        <a href="#">',
'         <i class=''bx bx-cart-alt''></i>',
'         <span class="links_name">Order</span>',
'        </a>',
'        <span class="tooltip">Order</span>',
'      </li>',
'      <li>',
'        <a href="#">',
'         <i class=''bx bx-heart''></i>',
'         <span class="links_name">Saved</span>',
'        </a>',
'        <span class="tooltip">Saved</span>',
'      </li>',
'      <li>',
'        <a href="#">',
'         <i class=''bx bx-cog''></i>',
'         <span class="links_name">Setting</span>',
'        </a>',
'        <span class="tooltip">Setting</span>',
'      </li>',
'     </ul>',
'     <div class="content">',
'       <div class="user">',
'         <div class="user_details">',
'           <img src="#APP_IMAGES#logo.png" alt="">',
'           <div class="name_job">',
'             <div class="name">jABER IT LTD</div>',
'             <div class="job">Apex Developer</div>',
'           </div>',
'         </div>',
'         <i class=''bx bx-log-out'' id="log_out"></i>',
'       </div>',
'     </div>',
'   </div>',
'   ',
'<script>',
'',
'let btn = document.querySelector("#btn");',
'let sidebar = document.querySelector(".sidebar");',
'let searchBtn = document.querySelector(".bx-search");',
'',
'btn.onclick = function(){',
'    sidebar.classList.toggle("active");',
'}',
'searchBtn.onclick = function(){',
'    sidebar.classList.toggle("active");',
'}',
'',
'',
'',
'</script>',
'</body>',
'</html>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp.component_end;
end;
/
