prompt --application/pages/page_00058
begin
--   Manifest
--     PAGE: 00058
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.3'
,p_default_workspace_id=>12825755979766489243
,p_default_application_id=>95068
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSTOCK'
);
wwv_flow_imp_page.create_page(
 p_id=>58
,p_user_interface_id=>wwv_flow_imp.id(14551754411696634465)
,p_name=>'Order tracking progress bar'
,p_alias=>'ORDER-TRACKING-PROGRESS-BAR'
,p_step_title=>'Order tracking progress bar'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.mismatch { background: #fee; font-weight: bold }',
'span.annot { margin:2px 2px 2px 3em; border:1px dotted #88f; background:#eef;',
'             padding: 0 2px 0 2px }',
'.nocode { background: #f8f8f8 }',
'',
'#P58_STATUS_VALUE {',
'    border-radius: 12px;',
'    background-color: rgb(210 210 210);',
'    font-size: 18px;',
'    font-weight: 900;',
'    color: black;',
'}',
'a {',
'    -webkit-text-decoration-skip: objects;',
'    color: #ffffff;',
'}',
'',
'img#idd2,#idd2,img#idd3,#idd3,img#idd4,#idd4 {',
'    MARGIN-LEFT: 22px;',
'}',
'',
'ol.progtrckr li {',
'    display: inline-block;',
'    text-align: center;',
'}',
'',
'',
'.arrow-steps .step {',
'	font-size: 14px;',
'	text-align: center;',
'	color: #fff;',
'	cursor: default;',
'	margin: 0 9px;',
'	padding: 6px 10px 10px 30px;',
'	min-width: 160px;',
'	float: left;',
'	position: relative;',
'	background-color: #7a736e;',
'	-webkit-user-select: none;',
'	-moz-user-select: none;',
'	-ms-user-select: none;',
'	user-select: none; ',
'  transition: background-color 0.2s ease;',
'}',
'',
'.arrow-steps .step:after,',
'.arrow-steps .step:before {',
'	content: " ";',
'	position: absolute;',
'	top: 0;',
'	right: -17px;',
'	width: 0;',
'	height: 0;',
'	border-top: 19px solid transparent;',
'	border-bottom: 17px solid transparent;',
'	border-left: 17px solid #7a736e;	',
'	z-index: 2;',
'  transition: border-color 0.2s ease;',
'}',
'',
'.arrow-steps .step:before {',
'	right: auto;',
'	left: 0;',
'	border-left: 17px solid #fff;	',
'	z-index: 0;',
'}',
'.arrow-steps .step:first-child:before {',
'	border: none;',
'}',
'.arrow-steps .step.current {',
'	background-color: green;',
'}',
'.arrow-steps .step.current:after {',
'	border-left: 17px solid green;	',
'}',
''))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'10'
,p_last_updated_by=>'JABER0181@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220729111133'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(13978783329618134336)
,p_plug_name=>'Order tracking'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(13978783524694134338)
,p_plug_name=>'Tracking Status'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(14551664721457634427)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    l_app            NUMBER := v (''APP_ID'');',
'    l_session        NUMBER := v (''APP_SESSION'');',
'',
'    CURSOR c_check_open IS',
'        SELECT 1',
'          FROM DUAL arh',
'         WHERE :P58_STATUS_VALUE IN (1,',
'                                     2,',
'                                     3,',
'                                     4,',
'                                     5,',
'                                     6);                      --Order Received',
'',
'    l_open_check     VARCHAR (10);',
'',
'    CURSOR c_check_assign IS',
'        SELECT 1',
'          FROM DUAL drh',
'         WHERE :P58_STATUS_VALUE IN (2,',
'                                     3,',
'                                     4,',
'                                     5,',
'                                     6);                             --Shipped',
'',
'    l_assign_check   VARCHAR (10);',
'',
'    CURSOR c_check_fwd IS',
'        SELECT 1',
'          FROM DUAL ph',
'         WHERE :P58_STATUS_VALUE IN (3,',
'                                     4,',
'                                     5,',
'                                     6);                      --Carrier Pickup',
'',
'    l_fwd_check      VARCHAR (10);',
'',
'    CURSOR c_check_cls IS',
'        SELECT 1',
'          FROM DUAL cih',
'         WHERE :P58_STATUS_VALUE IN (4, 5, 6);                   --Appointment',
'',
'    l_cls_check      VARCHAR (10);',
'',
'    CURSOR c_check_arr IS',
'        SELECT 1',
'          FROM DUAL sss',
'         WHERE :P58_STATUS_VALUE IN (5, 6);              --Arrived at Customer',
'',
'    l_cls_arr        VARCHAR (10);',
'',
'    CURSOR c_check_del IS',
'        SELECT 1',
'          FROM DUAL ccc',
'         WHERE :P58_STATUS_VALUE = 6;                              --Delivered',
'',
'    l_cls_del        VARCHAR (10);',
'BEGIN',
'    HTP.p (''<ol class="progtrckr" data-progtrckr-steps="5">'');',
'',
'    --htp.p(''<ol >'');',
'    OPEN c_check_open;',
'',
'    FETCH c_check_open INTO l_open_check;',
'',
'    IF c_check_open%FOUND',
'    THEN',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Order Received</b></a></span> </div>'');',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Order Received</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_open;',
'',
'    OPEN c_check_assign;',
'',
'    FETCH c_check_assign INTO l_assign_check;',
'',
'    IF c_check_assign%FOUND',
'    THEN',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Shipped</b></a></span> </div>'');',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Shipped</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_assign;',
'',
'',
'    OPEN c_check_fwd;',
'',
'    FETCH c_check_fwd INTO l_fwd_check;',
'',
'    IF c_check_fwd%FOUND',
'    THEN',
'        --for i in l_fwd_check.first..l_fwd_check.last loop',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Carrier Pickup</b></a></span> </div>'');',
'    -- end loop;',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Carrier Pickup</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_fwd;',
'',
'    OPEN c_check_cls;',
'',
'    FETCH c_check_cls INTO l_cls_check;',
'',
'    IF c_check_cls%FOUND',
'    THEN',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Appointment</b></a></span> </div>'');',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Appointment</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_cls;',
'',
'    OPEN c_check_arr;',
'',
'    FETCH c_check_arr INTO l_cls_arr;',
'',
'    IF c_check_arr%FOUND',
'    THEN',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Arrived at Customer</b></a></span> </div>'');',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Arrived at Customer</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_arr;',
'',
'',
'    OPEN c_check_del;',
'',
'    FETCH c_check_del INTO l_cls_del;',
'',
'    IF c_check_del%FOUND',
'    THEN',
'        HTP.p (',
'               ''<div class="arrow-steps clearfix">',
'          <div class="step current"> <span><a href="''',
'            || APEX_UTIL.prepare_url (',
'                   p_url      =>',
'                          ''f?p=''',
'                       || l_app',
'                       || '':186:''',
'                       || l_session',
'                       || ''::::P186_REQ_NO:''',
'                       || :p185_incident,',
'                   p_dialog   => ''null'')',
'            || ''"><b>Delivered</b></a></span> </div>'');',
'    ELSE',
'        HTP.p (''<div class="arrow-steps clearfix">',
'          <div class="step"> <span><b>Delivered</b></span> </div>'');',
'    END IF;',
'',
'    CLOSE c_check_del;',
'',
'    HTP.p (''</ol>'');',
'END;'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(13978783427468134337)
,p_name=>'P58_STATUS_VALUE'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(13978783329618134336)
,p_prompt=>'Status Value'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select level d, level r from dual ',
'connect by level<=6;'))
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_tag_attributes=>'onchange="apex.submit();"'
,p_field_template=>wwv_flow_imp.id(14551727356915634453)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'onchange="apex.submit(''P58_STATUS_VALUE'');"',
'apex.region("empRgn").refresh();',
'onchange="apex.submit();"',
'onchange="apex.region.refresh(''P25_STATUS_VALUE'');"',
'',
'onchange="apex.region("emp").refresh(''P25_STATUS_VALUE'');"',
'',
'onchange="apex.region("emp").refresh(''P25_STATUS_VALUE'');"',
'onchange="$("#P25_STATUS_VALUE").trigger(''apexrefresh'');"',
'',
'/*',
'function refresh() {',
'    apex.region("progtrckr").refresh();',
'}',
'',
'',
'function refreshCalendar() {',
'  window.setTimeout(function() {',
'    $("#P25_STATUS_VALUE").progtrckr("apexrefresh");',
'  }, 50);',
'}',
'',
'/*',
'',
'',
'',
'/*',
'<script language="JavaScript" type="text/javascript">',
'	function fnc_hide(){',
'        $("progtrckr").trigger(''apexrefresh'');        ',
'        }',
'</script>',
'',
'',
'',
'<script type="text/javascript">',
'apex.jQuery( function() {',
'    apex.page.init( this, function() {',
'        try {',
'            (function(){apex.jQuery(''body'').addClass(''t-PageBody--leftNav'');})();',
'            (function(){apex.widget.selectList("#P25_STATUS_VALUE",{"nullValue":"","ajaxIdentifier":"SVRFTSBUWVBFfjUxMjB-MTA4MjU2NDUwMzMyNDQ5NTEw\u002F1AD2MXeQoyborliCdGCloWNssxzl0B92IEpn5vNclxKPQNed1mPLCJM2uSDtG79BZWO4kTYFb8qLj1RjfnOW7w"});})();',
'            } catch(e) {apex.debug.error(e)};',
'            apex.jQuery.when.apply( apex.jQuery, apex.page.loadingDeferreds ).done(function() {',
'                try {',
'                    apex.theme42.initializePage.noSideCol();',
'                    apex.page.warnOnUnsavedChanges();',
'                    } finally {',
'                        apex.event.trigger(apex.gPageContext$,''apexreadyend'');',
'                        };',
'                    });',
'            });',
'        });',
'</script>',
'',
'*/'))
);
wwv_flow_imp.component_end;
end;
/
